### ISSUE TITLE
Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by KostovVN** [TeamWertarbyte/material-ui-chip-input#101]
warning.js:36 Warning:Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/src/ChipInput.js#L112

**Comment by leMaik** [comment]
This was already fixed, see #100. Please update to v0.13.2.

**Comment by leMaik** [comment]
Sorry, you are absolutely right! I'll fix this asap.

**Comment by KostovVN** [comment]
Thank!
