### ISSUE TITLE
Chip input as part of a formula editor

### ISSUE THREAD

**Issue by keithamoss** [TeamWertarbyte/material-ui-chip-input#103]
(Firstly, thanks for putting together a great project!)

We're looking at using material-ui-chip-input as part of an inline formula editor, but from what we can see of the documentation there's a few extra features we'd need to add support for. Before we embark on that exercise we wanted to check if you either had any plans for these features, and that you weren't philosophically opposed to adding them to this project.

We're looking to create something akin to the Apple Numbers inline formula editor.

![download](https://cloud.githubusercontent.com/assets/1672960/25258920/6511b0fe-2675-11e7-808b-2d10b7bd6b32.png)

We believe we'd need to add the following enhancements into or on top of material-ui-chip-input:

- Allowing the user to enter plain text characters in the field that don't get turned into chips. (In this case, a limited set of special characters to express basic mathematical operations.)

- Allowing the user to navigate through the field value using keyboard or mouse to edit non-chip characters.

- Allowing the user to click anywhere in the field, type a string representing a valid chip, choose it from an autocomplete dropdown, and have the chip inserted at the current position of the text input caret.

- All of the above may also require a means of defining a filter on the input that takes in an input string of characters and splits it up into the portion that should be plain text (which is discarded) and the portion that should be fed to autocomplete to be turned into a chip (in our case, a simple regular expression match for the chip will suffice).

- Defining a function that will validate the whole input's value and set the `errorText` to provide hints to the user.

Beyond these we also have requirements (which you and material-ui itself already support!) for dynamically setting the colour of the input according to a filter of our own design, clicking chips to open a tooltip/populate an element with more information, and deleting a chip by clicking to close it.

Thanks for your time :)

**Comment by leMaik** [comment]
Hi, @keithamoss!
That sounds like a very great component you are going to code there. :+1: I believe that this is far out of scope, though. This project aims to solve exactly one problem, i.e. provide a chip input control for Material-UI. Your component has a lot of additional requirements, especially optical changes, so I think it would be better to bake all that in a new component. :wink: 
There are lots of people who use this component already, so let's not bloat them with features that most of them don't need.

That said, everything is open source :rainbow:, so you are welcome to re-use the existing code (or even fork this project) and I'd love to see the inline formular editor in action. :tada:

**Comment by keithamoss** [comment]
No problems, @leMaik! Once I'd finished typing all of that I'd sat back and kinda reached the same conclusion myself. Will ping you when we have something working - very likely based on your good works here :)
