### ISSUE TITLE
How can we reset the component internal state ?

### ISSUE THREAD

**Issue by CyrilQuandalle** [TeamWertarbyte/material-ui-chip-input#104]
Hi,

I'm working on an app  with multiple internal tabs, I've managed to have a state for each tab with a higherOrder reducer. With your component keeping its internal state accross tabs I have some random behaviour, is it possible to reset it ?

thanks in advance

Cyril

**Comment by leMaik** [comment]
Which state does the component keep? It shouldn't keep any state when it is used in controlled mode (i.e. when using `value` and `onChange`).

**Comment by CyrilQuandalle** [comment]
Hi,

Sorry it was actually a bug on my side I was mutating the initialState at some point
And indeed it woud be an ugly workaround ;-).
