### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by hoppula** [TeamWertarbyte/material-ui-chip-input#105]
Hi and thanks for the great project. 

Our app unfortunately has to support IE11 and I noticed that you're using `Array.prototype.find()` on https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/src/ChipInput.js#L310 

`Array.prototype.find()` is supported only on IE Edge, so I was wondering if you could use some other Array method or possibly even https://github.com/lxe/babel-plugin-transform-array-find ?

**Comment by leMaik** [comment]
I just replaced `.find` with `.some`, which does the same thing in that line.
Could you please try the latest commit and tell me if it works on IE11?

**Comment by hoppula** [comment]
Thanks for the super fast response, just tested latest master using local build and it's working fine now 👍

**Comment by leMaik** [comment]
Great! I'm releasing a new patch version that resolves this issue right now. :+1:

**Comment by hoppula** [comment]
Thank you! 👏
