### ISSUE TITLE
Allow displaying the hintText when chips are already added

### ISSUE THREAD

**Issue by pvjones** [TeamWertarbyte/material-ui-chip-input#107]
Hi, I've incorporated material-ui-chip-input with redux-form and it's working beautifully. However, I have a hintText prop that's successfully getting passed to the chip input, but the text will not render. I'm not sure how to troubleshoot the issue. Any help would be greatly appreciated.

**Comment by leMaik** [comment]
I'm afraid I can't reproduce this, neither with material-ui 0.17.4 nor with 0.18.0. :confused:

**Comment by pvjones** [comment]
Ok I'm a n00b--sorry for the false alarm. This was based on a simple misunderstanding of hintText functionality on my part. It's working as intended. I was assuming/hoping that hintText would show even if the chip-input was pre-populated with values from the store. 

Do you know if there would be any way to force display of hintText even if there are chips present?

**Comment by leMaik** [comment]
Displaying the hint text even if there are chips when the text field for entering a new chip is empty is not possible yet, but I think it's a good idea! :+1: 
I'll add that as soon as I can...

**Comment by yuzhakovvv** [comment]
@leMaik Any updates here?

**Comment by leMaik** [comment]
@yuzhakovv Sorry, completely forgot this one. Would you like to submit a PR? :+1:

**Comment by leMaik** [comment]
This was done in #253 :tada:
