### ISSUE TITLE
Keep popover open

### ISSUE THREAD

**Issue by leMaik** [TeamWertarbyte/material-ui-chip-input#11]
In #8, the following improvement was suggested:

> Also would it be possible, when "openOnFocus" is true, to keep the popover opened (it would close only on clickaway from the component's main container). Explanation: an input using chipS is not supposed, at least in general usages, to use only one Chip. So it would be more userfriendly to have the popover opened to multiselect several options at once.

**Comment by Sharlaan** [comment]
i've tried this
```
handleInputBlur = (event) => {
  console.debug('input blurred !')
  if (this.autoComplete.refs.menu) {
    const menuHTMLnode = ReactDOM.findDOMNode(this.autoComplete.refs.menu)
    const focusedElt = event.relatedTarget
    if (menuHTMLnode.contains(focusedElt)) {
      console.debug('Focusing input without closing menu !')
      this.autoComplete.refs.searchTextField.focus()
    } else {
      console.debug('closing menu !')
      this.autoComplete.close()
      this.setState({ isFocused: false, inputValue: '' })
    }
  }
  if (this.props.onBlur) this.props.onBlur(event)
}

handleInputFocus = (event) => {
  console.debug('input focused !')
  if (this.props.disabled) return;
  this.setState({isFocused: true, open: true});
  if (this.props.onFocus) this.props.onFocus(event);
}
```
it should work ... but something else is closing the menu right after. i couldnot figure out what (without rewriting whole AutoComplete component).

**Comment by leMaik** [comment]
Maybe we should wait with this until the `next` branch of Material-UI is released. It's a full rewrite and it might make this simpler.

**Comment by Sharlaan** [comment]
Let's hope yes

**Comment by acomito** [comment]
any update on this?

**Comment by leMaik** [comment]
@acomito Not yet. :disappointed: Do you have any idea on how to implement this?

**Comment by acomito** [comment]
I may have misinterpreted what was asked for here. I just added `openOnFocus` and got the functionality I needed.

p.s. great package

**Comment by zigzackattack** [comment]
This would be a great feature! It's also how [react-select](http://jedwatson.github.io/react-select/) behaves.

**Comment by saitonakamura** [comment]
maybe we could do something with Autocomplete `open` prop as a workaround?
something like use `setState` to keep it and change it by subscribing to `onBlur` and other events?

**Comment by leMaik** [comment]
It's been a while and nobody seems to have a solution. Also, Material-UI v0 is deprecated, so I'll close this.
