### ISSUE TITLE
Console warning when using with material-ui@0.18.0

### ISSUE THREAD

**Issue by rsolomon** [TeamWertarbyte/material-ui-chip-input#110]
`npm WARN material-ui-chip-input@0.13.5 requires a peer of material-ui@>= 0.15.0 <= 0.17.x but none was installed.`

The only breaking change in 0.18.0 is one with tables, which should not affect this lib.

**Comment by leMaik** [comment]
I just updated the material-ui peer dependency to `< 1.0.0`. If anything breaks with 0.x.x releases in the future, that should be considered a bug.
Thanks for the hint.
