### ISSUE TITLE
Update value when default value is updated and the value didn't change in uncontrolled mode

### ISSUE THREAD

**Issue by aditya2337** [TeamWertarbyte/material-ui-chip-input#111]
If I set the default value set to a value set from the state and if in future the state changes(like in componentDidReceiveProps) the default value does not displayed as the selected chip.

**Comment by leMaik** [comment]
That's the way `defaultValue` works. If you want to modify the selected chips, you have to use _controlled mode_ and set the `value` prop accordingly.

**Comment by leMaik** [comment]
Feel free to re-open this, if you think that it is a bug. :wink: 
You may want to take a look at the examples [here](https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/stories/) for further help.

**Comment by aditya2337** [comment]
But If I am fetching some data from some api and then I set the state of the `defaultValue` according to the response of the api call, it should technically call the render function again, hence the `defaultValue` sholud be changed showing me the selected default chip, but it currently does not work that way and I feel it still is a bug, I don't want to use controlled mode and want to keep it simple.

**Comment by leMaik** [comment]
Controlled mode _is_ simple. :sweat_smile: I won't "fix" this bug, as it isn't a bug. Your app state changes by fetching data, so you want to change this component's value, and that's what the `value` prop is there for, I'm afraid. :confused:

**Comment by aditya2337** [comment]
I have tried that trust me, If I am using the `value` prop, I am unable to cross out any chip, I might be missing something here but it gets all weird when I use the `value` prop

**Comment by leMaik** [comment]
You also need to update your `value` value in the `onChange` handler. Please take a look at the examples, especially the controlled example. :wink: That's how many React components work!

**Comment by aditya2337** [comment]
Ah see with controlled mode you have the `handleRequestAdd` and the `handleRequestDelete` which are two functions right, but when I say I want to keep it simple I mean by my one function doing both the things that is the `onChange` function, which I feel should be possible.

**Comment by aditya2337** [comment]
I know its not that complex but still I feel it is a bug

**Comment by leMaik** [comment]
I agree that having both, `onRequestAdd` _and_ `onRequestDelete` might not be the best architecture, but this is not a bug. :wink: 

After some thinking, I _think_ that I could do the following: If the actual value of the chip input did not change (i.e. is the same _reference_ as `defaultValue`) and the `defaultValue` is updated, I could change the actual value to the new default value.

I'd see this as an enhancement and not as a bug, though, because it's not the way it works with any Material UI component and controlled mode intentionally gives you more control than uncontrolled mode. :wink:

**Comment by BaptWaels** [comment]
Hi,
Any updates about this enhancement ?

If needed, I could create a PR

**Comment by leMaik** [comment]
Done, thanks to @BaptWaels for the PR! :tada:
