### ISSUE TITLE
In v1.0.0, make onRequestAdd and onRequestDelete consistent

### ISSUE THREAD

**Issue by advance512** [TeamWertarbyte/material-ui-chip-input#112]
onRequestAdd receives an object (if you use dataSource and dataSourceConfig) while onRequestDelete receives a string, being just the value of the item in the data source.

e.g.

```
onRequestAdd({ label: "Some label", value: "SOME_ENUM_VALUE"});
onRequestDelete("SOME_ENUM_VALUE");
```

You get the item in one, the value in another. Sure, sometimes the item is a string, sometimes it contains a text/label and the value string.

Seems to me that it would be more consistent to stick to either value or the complete item.

This ticket's source is the conversation in ticket #52.

**Comment by leMaik** [comment]
Since there might not be a _complete item_ if no `dataSource` is used (i.e. only string values), we'll stick to strings in that case.

**Comment by leMaik** [comment]
Only took two years to fix. :see_no_evil:
