### ISSUE TITLE
Unable to delete chip

### ISSUE THREAD

**Issue by VinceRao** [TeamWertarbyte/material-ui-chip-input#113]
It can reproduce in storybook
Step:
1. open the storybook
2. try to click the x on the chip to delete but the chip still there

**Comment by VinceRao** [comment]
The reason is the storybook has been configured before the injectTapEventPlugin has been called, switch the order will fix the problem.

**Comment by leMaik** [comment]
Thank you, I've pushed a fix and will redeploy the storybook in a few minutes.
