### ISSUE TITLE
Customizing Chip Styles

### ISSUE THREAD

**Issue by sameer-bridg** [TeamWertarbyte/material-ui-chip-input#12]
Hi!

First of all, fantastic job with this component! 

Is there any way to customize the style of the component (background, color, etc.) and what about adding an icon? (ref: http://www.material-ui.com/#/components/chip)

**Comment by leMaik** [comment]
Thank you very much!

This is not possible yet, but it could be done if I add a `renderChip` prop that may contain a function that gets the chip value and returns a chip node.
Like this: `<ChipInput chipRenderer={(value) => <YourCustomChip value={value} />} />`

Would this approach suit your needs?
