### ISSUE TITLE
Optional allowCustomValue prop

### ISSUE THREAD

**Issue by wesley6j** [TeamWertarbyte/material-ui-chip-input#120]
There are some situations that creating new values by pressing enter may not be desired? (select users to create a group, but creating a new user needs more that a name).

**Comment by arlen-yu** [comment]
I think that it already has this capability (if I am understanding you correctly), see `newChipKeyCodes` prop.

**Comment by wesley6j** [comment]
@arlen-yu Thanks. This solves my problem.
