### ISSUE TITLE
Only line break if your text will overflow

### ISSUE THREAD

**Issue by arlen-yu** [TeamWertarbyte/material-ui-chip-input#121]
Hi, is it possible to have the ability to only line break if the text will overflow? Right now the text field will automatically carriage return if it feels it doesn't have sufficient space, even when no text is typed yet. Having the carriage return looks a bit clunky sometimes.

**Comment by leMaik** [comment]
Maybe you're right, but I think that wrapping while typing would feel a bit strange too, wouldn't it?

**Comment by arlen-yu** [comment]
Yea that's true. How about instead of wrapping, the carrot only jumps to the next line when the user typing reaches the max capacity. 

Or, is there any way to manually control the width of the input field (rather than text field)?

**Comment by wesley6j** [comment]
@arlen-yu  This is how `AutoComplete` set its width: `width: fullWidth ? '100%' : 256`.
So you will have to wrap it in a div with the `width` you want and then pass `fullWidth=true` to `AutoComplete`.

One problem I can think of is that, by default, the choices list with be of the same width as input field. So when you have only entered a few letters, the choices list will be hard to read.

**Comment by bradrisse** [comment]
Add fullWidth to make it display on one line, input style to keep it from going to the next line too soon, and chipContainer to auto so it doesn't inherit the 100%

```<ChipInput fullWidth inputStyle={{width: 50}} chipContainerStyle={{width: 'auto'}} defaultValue={['foo', 'bar']} />```
