### ISSUE TITLE
You cannot call prepareStyles() on the same style object more than once

### ISSUE THREAD

**Issue by cyrus-za** [TeamWertarbyte/material-ui-chip-input#123]
I get the following error when using it with **redux-form**
`browser.js?fe34ab5:49 Warning: Material-UI: You cannot call prepareStyles() on the same style object more than once.`

```javascript
import { MuiThemeProvider } from "material-ui";
import { Field, reduxForm } from "redux-form";
import ChipInput from 'material-ui-chip-input'

const muiTheme = getMuiTheme({
    userAgent: false,
    palette: {
        primary1Color: teal,
        primary2Color: watermelon,
    },
});

const MyAwesomeComponent = ({handleSubmit}) =>
  <MuiThemeProvider muiTheme={muiTheme}>
    <form onSubmit={handleSubmit}>
        <Field name="testChipInput" component={ChipInput} dataSource={[1,2,3,4]}/>
    </form>
  </MuiThemeProvider>

export default reduxForm({
    form: 'MyAwesomeComponent'
})(MyAwesomeComponent));
```

**Comment by leMaik** [comment]
After a first look, I don't see where we call `prepareStyle` on the same object. :thinking: Do you have any idea?

**Comment by cyrus-za** [comment]
I think material-ui calls it. I am not sure what triggers it. Probably the onChange callback.

**Comment by leMaik** [comment]
So... How am I supposed to fix this? :sweat_smile:

**Comment by cyrus-za** [comment]
It only occurs with your component. No other material ui component.

**Comment by leMaik** [comment]
Allright, I'll try to reproduce the error. I still have no idea what causes it, as we re-create the style object on each `render()` call.

**Comment by cyrus-za** [comment]
Thanks for checking it out. If you know of a easy way to host the example, let me know. I can't seem to find a cdn for material-ui and JS-bin don't have it in their list of libraries. I'm not sure what people use these days for react to demonstrate issues. Does JSFiddle have all the required libraries maybe?

**Comment by leMaik** [comment]
I just submitted a PR to Material-UI that fixes this warning. Using the chip input with redux-form works fine, it only shows lots of warnings in the console. :confused:

**Comment by cyrus-za** [comment]
Have you successfully used it with redux-form where the value actually gets updated via redux-form? For me, the initial values get loaded and the component shows the selected values, but it doesn't actually get sent in the handleSubmit callback from redux-form.

**Comment by leMaik** [comment]
Well, I tried the example you provided and it worked. I didn't try to submit the form. :wink:  Also, I submitted a PR to Material-UI that fixes _this_ issue. Feel free to open a new one for the submission problem.

**Comment by cyrus-za** [comment]
Once the PR goes through I'll update MUI and check if it submits correctly when there's no longer a error message as I suspect the reason it doesn't update the value is due to erroring out.

**Comment by leMaik** [comment]
The error message came from [here](https://github.com/callemall/material-ui/blob/master/src/utils/callOnce.js#L9). I don't think that the `warning` actually throws an exception, so I guess that the submission error is related to something else. I'll investigate the problem this weekend.

**Comment by leMaik** [comment]
@cyrus-za I it with the Material-UI patch applied. It doesn't work, the value of the form field just doesn't get updated.

**Comment by cyrus-za** [comment]
@leMaik I'm not sure what `I it with` means. I think there's a word missing in that sentence :)

So we just waiting on them to release a update?

**Comment by leMaik** [comment]
@cyrus-za Well, it was pretty late. :sweat_smile: I meant to say "I tried it with the Material-UI patch applied." The warning is gone, but the form still doesn't get any value and I couldn't figure out why. :confused:

**Comment by cyrus-za** [comment]
ah ok. May I ask, how have you been using this component? Do you just not use redux-form or what?

**Comment by leMaik** [comment]
I used it with redux as well as with `setState` and it worked just fine. Never heard of redux-form before this issue.

**Comment by cyrus-za** [comment]
redux-form is the best thing since cheese. https://youtu.be/eDTi7lYR1VU

**Comment by leMaik** [comment]
Thank you, I'll give it a try in the next project. :+1: Still don't understand why it doesn't want to work with the chip input, though, even after re-reading the docs and looking at the tutorials. :confused:
