### ISSUE TITLE
Pass the dataSource value directly in chipRenderer

### ISSUE THREAD

**Issue by oktay-sen** [TeamWertarbyte/material-ui-chip-input#129]
When using chipRenderer with objects in the dataSource, we only have access to text and value, when we could have access to the dataSource object directly. I'd like to be able to use other variables inside the dataSource object, like avatarUrl or backgroundColor. Looking at the source code, this seems to be a 1 line change, and I think it would be very useful for everyone.

**Comment by leMaik** [comment]
Would you like to create a PR that changes that one line without breaking backward-compatibility? :wink:

**Comment by oktay-sen** [comment]
Added pull request #130 :)
