### ISSUE TITLE
onSubmit always returns empty array

### ISSUE THREAD

**Issue by stavlocker** [TeamWertarbyte/material-ui-chip-input#132]
Hey guys, very nice project. Looking forward to see the v1 integration. But I'm experiencing an issue: Submitting the form doesn't pass the chips added. You can see this in the [storybook](https://teamwertarbyte.github.io/material-ui-chip-input/?selectedKind=ChipInput&selectedStory=in%20a%20form&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel).

**Comment by leMaik** [comment]
How should it? There is no code that would add the chip's input to the values that get submitted in that example.
