### ISSUE TITLE
Assign value to chip

### ISSUE THREAD

**Issue by stavlocker** [TeamWertarbyte/material-ui-chip-input#133]
Is there a way to assign a certain value to a chip? For example, I want the text to say `xyz` but I want the value (that will be passed onto onSubmit for example) will be `abc`. This way there may be two chips that have the same text but have different values so they're allowed. It'd be great to see this in the project.

I for example need this because I'm making an "invite people" form and this way I can present their Full name but have their username passed on.

**Comment by leMaik** [comment]
This is possible by using the `chipRenderer` prop, which gets (among others) the raw object.

**Comment by juanda99** [comment]
Any update on this?
I'm just trying to implement it, see: 
[![Edit jz5r521oj5](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jz5r521oj5).

I'm not sure why chipRenderer is needed as it render {text} by default. In my case I just copy-paste the default function.
However I have to problems:
- My chips are initialized as objects with 2 keys (values, and objects). It should be better to take just the value and get the current text from the datasource (let's say something like index = datasource.findIndex(x => x.value==this.props.value). But I don't get access to dataSource from chipRendered function :-( Any idea?
- Chip can get render twice with the same text (autocomplete just offer the text once, second time, writing it down it gets that text also as value). It could be handle from onRequestAdd so it's not a problem.
