### ISSUE TITLE
Cannot overwrite the error text color like in MaterialUI TextField

### ISSUE THREAD

**Issue by simnau** [TeamWertarbyte/material-ui-chip-input#136]
https://github.com/TeamWertarbyte/material-ui-chip-input/blob/858aa48e90472fb262006991c3fe0f6e39747744/src/ChipInput.js#L463
It's impossible to style the ChipInput's error text color in the way it's possible using a MaterialUI TextField.
This changes the underline and the error text color to orange in MaterialUI:
`
<TextField 
  errorStyle={{ color: 'orange' }}
/>
`
This changes only the underline color but not the error text color in ChipInput:
`
<ChipInput
  errorStyle={{ color: 'orange' }}
/>
`

**Comment by leMaik** [comment]
Thanks for the report, the fix is released as v0.16.1 :+1:
