### ISSUE TITLE
Remove dependency to `react-tap-event-plugin`

### ISSUE THREAD

**Issue by rsolomon** [TeamWertarbyte/material-ui-chip-input#137]
material-ui@0.19.0 removed all dependencies for `react-tap-event-plugin`, and all usages of `onTouchTap`. It instead just uses `onClick` for all click/touch interaction events. More information can be found [here](https://github.com/callemall/material-ui/releases/tag/v0.19.0).

`material-ui-chip-input` still depends on `react-tap-event-plugin` / `onTouchTap`, and throws console warnings when used with mui@0.19.0.

**Comment by leMaik** [comment]
Thank you for the PR! :tada: It's a bit sad that there is a breaking change in material-ui 0.x while 1.0.0 is already in beta, but yeah... :roll_eyes: Guess we'll have to update all of our components... twice.

**Comment by djhi** [comment]
Hi! Can you release this change? :pray:

**Comment by leMaik** [comment]
@djhi Thanks for the reminder, I'll release it this evening.

**Comment by leMaik** [comment]
@djhi Done: https://github.com/TeamWertarbyte/material-ui-chip-input/releases/tag/v0.17.0 :tada:

**Comment by djhi** [comment]
:tada: ! Thanks !
