### ISSUE TITLE
Problem in supporting IE 11 in production mode

### ISSUE THREAD

**Issue by vijaykunapareddy** [TeamWertarbyte/material-ui-chip-input#139]
I am using material-ui-chip-input in my popup, it is working good in Chrome, but not supporting in IE 11 in production mode . Please let me know whether material-ui-chip-input supports IE 11 or not.

Thanks,

**Comment by leMaik** [comment]
Could you please provide some stack traces / error messages? If there is a not too complicated fix, I'll try to make it work with IE 11.

**Comment by vijaykunapareddy** [comment]
Sorry, It's my bad, actually I had problem with material-ui-chip component not material-ui-chip-input.
I got update from material- ui team. Anyway thanks for your reply. Appreciated.
