### ISSUE TITLE
onChange callback contains duplicated value when adding

### ISSUE THREAD

**Issue by liuyang1204** [TeamWertarbyte/material-ui-chip-input#14]
When adding a chip, onChange callback includes 2 values of the added chip.

**Comment by leMaik** [comment]
I can't reproduce this, neither in controlled nor in uncontrolled mode. Could you please post your code?

**Comment by leMaik** [comment]
The commit mentioned above may fix this issue. Could you please re-check this?

**Comment by liuyang1204** [comment]
@leMaik Tested, it works, thanks!

**Comment by pramttl** [comment]
I am able to replicate the same issue. The last selected chip is duplicated in the `chips` array passed on to `onChange` handler.

**Comment by leMaik** [comment]
@pramttl Could you please try it with the new `v0.4.1` that I published a few minutes ago?

**Comment by pramttl** [comment]
@leMaik Perfect. No duplication anymore.

**Comment by leMaik** [comment]
Solved in `v0.4.1`.
