### ISSUE TITLE
controlled chipinput objects as chips

### ISSUE THREAD

**Issue by marutha** [TeamWertarbyte/material-ui-chip-input#141]
The example is not working, do we have an example source code?

https://teamwertarbyte.github.io/material-ui-chip-input/?selectedKind=ChipInput&selectedStory=objects%20as%20chips%2C%20controlled&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

**Comment by leMaik** [comment]
The code is fine, we just don't handle `onRequestAdd` properly. Please take a look at the other controlled examples to see how this event should be handled.
