### ISSUE TITLE
doesnt work on material-ui v0.19.1

### ISSUE THREAD

**Issue by muhilham** [TeamWertarbyte/material-ui-chip-input#143]
i just upgrade my module into material-ui v0.19.1 and suddenly event onChange and onRequestAdd doesnt work with ChipInput props. But if i downgrade my version material-ui v0.19.0 suddenly it work, any help ?

**Comment by leMaik** [comment]
Wow. material-ui bringing breaking changes to a patch update. Awesome! :confused: Just use v0.19.0 for now, we'll try to fix it soon.

**Comment by leMaik** [comment]
Wow. material-ui bringing breaking changes to a patch update. Awesome! :confused: Just use v0.19.0 for now, we'll try to fix it soon.

**Comment by muhilham** [comment]
it works with the new release v0.17.2 material-ui-chip-input. Thx @leMaik !!!

**Comment by leMaik** [comment]
@muhilham All credits to @umidbekkarimov! He fixed that. :sunglasses:

**Comment by muhilham** [comment]
you are my hero, dude ! @umidbekkarimov
