### ISSUE TITLE
Is possible to have some type of validation before adding a chip?

### ISSUE THREAD

**Issue by kalimantos** [TeamWertarbyte/material-ui-chip-input#145]
I'm trying to make a input for a mail "to" field, so chips are so useful, but before adding it i want to be sure that the input contains a valid email address. It is possible to do that?
Thank you

**Comment by leMaik** [comment]
That's possible by using the _controlled_ mode and then not adding invalid chips in the `onRequestAdd` handler.

**Comment by kalimantos** [comment]
yes thank you, but everytime i press enter the input is cleaned indipendently from whether the chip is added or not. How can i make that input not been cleared?

**Comment by leMaik** [comment]
Uhm… You can't, at the moment. Maybe we could add a `onBeforeRequestAdd` callback, that returns `true` or `false` for adding/not adding the chip which can then be used for validation. :thinking: 

What do you think?

**Comment by kalimantos** [comment]
it should be awesome!

**Comment by leMaik** [comment]
Would you like to implement this in a PR? :)

**Comment by kalimantos** [comment]
yep! give me few minutes

**Comment by leMaik** [comment]
Granted. :smile: No pressure, though. :wink:

**Comment by kalimantos** [comment]
let me know if it's ok ;)

**Comment by leMaik** [comment]
Merged, I'll release a new version in a few minutes.
