### ISSUE TITLE
material-ui v1 support

### ISSUE THREAD

**Issue by Jf881** [TeamWertarbyte/material-ui-chip-input#147]
When using material-ui@next ChipInput breaks because of changes to material-ui. For example:
Can't resolve 'material-ui/TextField/TextFieldUnderline'
Can't resolve 'material-ui/TextField/TextFieldHint'
...and material-ui/styles/colors has moved to material-ui/colors.
Any chance of an update soon?

Steps to reproduce:
>create-react-app example
>cd example
>yarn add material-ui@next
>yarn add material-ui-chip-input
Add "import ChipInput from 'material-ui-chip-input' " in App.js
>yarn start

Thx!
/J

**Comment by leMaik** [comment]
This component doesn't support v1 of material-ui yet. There are lots of breaking changes, unfortunately, so it will take a while. But we're definitely planning to support it!

**Comment by leMaik** [comment]
Uhm… Actually, this is a duplicate of #88

**Comment by Jf881** [comment]
Thx for superfast reply, missed that one.
/J
