### ISSUE TITLE
How to modify menuStyle, titleStyle and listStyle of the underlying AutoComplete?

### ISSUE THREAD

**Issue by marsonmao** [TeamWertarbyte/material-ui-chip-input#155]
As material-ui is supporting `menuStyle` and `listStyle` of `AutoComplete`, will the authors choose to add these props in the future so that we can customize the `AutoComplete` appearance?

To be very specific, I mean adding:
```
        <AutoComplete
          {...other}
          {...inputProps}
          filter={actualFilter}
          style={inputStyleMerged}
          dataSource={autoCompleteData}
          dataSourceConfig={dataSourceConfig}
          searchText={this.state.inputValue}
          underlineShow={false}
          ref={this.setAutoComplete}
          listStyle={ _ } // here!
          menuStyle={ _ } // here!
        />
```

**Comment by marsonmao** [comment]
Oh found another one, AutoComplete's `textFieldStyle`...this one is also very important, since it affects the width of this element

**Comment by leMaik** [comment]
All undocumented props are [passed down to AutoComplete](https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/src/ChipInput.js#L559), so your example should work just fine.

**Comment by marsonmao** [comment]
@leMaik You are right, and I was also pasting that part in my code snippet, so that was really a mistake. Thanks for your reply!

**Comment by leMaik** [comment]
Glad I could help you. 👍
