### ISSUE TITLE
material-ui-chip-input@0.12.2 requires a peer of material-ui@>= 0.15.0 <= 0.16.x but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by takealuke** [TeamWertarbyte/material-ui-chip-input#156]
Getting an npm warning: 

material-ui-chip-input@0.12.2 requires a peer of material-ui@>= 0.15.0 <= 0.16.x but none is installed. You must install peer dependencies yourself.

But unable to do npm install -save material-ui@>= 0.15.0 <= 0.16.x

Get an error:

npm ERR! code E404
npm ERR! 404 Not Found: 0.15.0@latest

**Comment by takealuke** [comment]
I restarted mu npm updates -- just did them over again -- and now there is no issue. . .  very strange (but closing this issue)

**Comment by leMaik** [comment]
The peer dependency is `material-ui`, `>= 0.15.0 <= 0.16.x` is the version range, so you just need to run `npm install --save material-ui`.
