### ISSUE TITLE
Add .babelrc to .npmignore

### ISSUE THREAD

**Issue by ashl1** [TeamWertarbyte/material-ui-chip-input#157]
## The case
* some of libs in npm registry provides only ES6 builds
* we want to support browsers with ES5 builds

## Solution we use
* enable `babel` for `node_modules` directory

## Problem
While Babel is run for files provided by npm, the Babel configuration is presented in the package.json file. But the already babelified js file will be used. Threfore our (external) Babel tries to use (internal) Babel config. The configuration between your package and our Babel might be different.

## Decision
Could you add the `.babelrc` file to `.npmignore`? And maybe `src/` directory?
If user wants to develop an app he will use Git sources with `.babelrc`. If he simply wants to use the builded form of your package, this won't be affected by the internal Babel settings.

**Comment by leMaik** [comment]
So… you recompile all dependencies… again? :fearful:

**Comment by ashl1** [comment]
Yep. Look at https://philipwalton.com/articles/deploying-es2015-code-in-production-today/
I'll make a PR tomorrow

**Comment by leMaik** [comment]
@ashl1 It's been some days, I'll just to this myself for the upcoming release. :wink:
