### ISSUE TITLE
chip autocomplete not working on react 16

### ISSUE THREAD

**Issue by natrim** [TeamWertarbyte/material-ui-chip-input#159]
chip autocomplete is not working on react 16 with material-ui 0.19
it does not add chip on click

reposted from https://github.com/marmelab/admin-on-rest/issues/1139

**Comment by leMaik** [comment]
@natrim I'm afraid I can't reproduce this with react@16 in [the updated storybook](https://teamwertarbyte.github.io/material-ui-chip-input/?selectedKind=ChipInput&selectedStory=with%20auto%20complete%2C%20custom%20filter%2C%20open%20on%20focus&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel).

Please feel free to reopen this when you have more information on how to reproduce this bug, though! :+1:

**Comment by gaurav414u** [comment]
Is it working guys?

**Comment by leMaik** [comment]
@gaurav414u As I said, I can't  reproduce this issue
