### ISSUE TITLE
Controlled chips calling onChange instead of onRequestAdd and onRequestDelete

### ISSUE THREAD

**Issue by liutongchen** [TeamWertarbyte/material-ui-chip-input#162]
I am using `ChipInput` as a controlled component and according to the document, if I use it as controlled components, adding and deleting a chip will call `onRequestAdd` and `onRequestDelete` 
if I understand correctly. But output of the following code indicates that `onChange` is called instead of `onRequestAdd` and `onRequestDelete` even when `ChipInput` has an attribute `value`.

I'm wondering whether it's because of the code I write that causes this problem? 

<img width="595" alt="create_farm_dialog_js_-_ecoation-code_-____documents_ecoation_ecoation-code_" src="https://user-images.githubusercontent.com/19363363/32471354-a9fa50fc-c311-11e7-8b2d-4f5a6bac3156.png">

Versions:
"material-ui": "latest",
"material-ui-chip-input": "^0.18.2"

**Comment by liutongchen** [comment]
Sorry, it's because some stupid typo I made when controlling the state.

**Comment by leMaik** [comment]
Allright, feel free to open a new issue if you have more questions. :+1:
