### ISSUE TITLE
Disabling the chip input also disables the current inputs in the chip.

### ISSUE THREAD

**Issue by chrisabrams** [TeamWertarbyte/material-ui-chip-input#163]
Is there a way to disable the text input, but not the current chips? Aka, make it to where a user cannot add, but they can delete?

**Comment by leMaik** [comment]
Why would you want to do that from a UX perspective? :open_mouth: Imagine if the user accidentially removes a chip…

**Comment by chrisabrams** [comment]
👍 

I ended up using the controlled input, and just don't add the chip if the max length is exceeded.

**Comment by leMaik** [comment]
@chrisabrams That sound's like a better option. You can also show a toast that informs the user about the invalid value using that approach. :+1:
