### ISSUE TITLE
Extensible styles or classnames for rendered elements.

### ISSUE THREAD

**Issue by jessemull** [TeamWertarbyte/material-ui-chip-input#165]
It is currently pretty difficult to target the nested divs, hint text, floating label etc. to apply custom styles. It would be great to either apply a class name or ID to each element. Willing to make the changes and submit a PR. Thanks.  - J

**Comment by leMaik** [comment]
This will be possible in the Material-UI 1.0.0-beta port that is coming soon. :+1:

See #88, I'll start it in the next week.

**Comment by leMaik** [comment]
This is possible in the 1.0.0-beta release that is coming soon. You can literally make rainbow chips now¹! :smile: 

¹There will be a demo in the storybook, it's even animated.
![image](https://user-images.githubusercontent.com/5544859/33528215-3e9972e6-d85d-11e7-9cae-4b4077063cbb.png)
