### ISSUE TITLE
default filter as caseInsensitive ?

### ISSUE THREAD

**Issue by Sharlaan** [TeamWertarbyte/material-ui-chip-input#17]
default filter is set as caseSensistive in v0.4.1

Would not it be better as caseInsensitive by default ?
(would just have to add .toLowerCase() to the filter function)

**Comment by leMaik** [comment]
Indeed, that would be cool. You'd have to use `.toLowerCase()` on the value the user typed _and_ the auto complete values for comparison, though.
Do you want to create a PR for this?

**Comment by Sharlaan** [comment]
me and PR = 2 ...

**Comment by leMaik** [comment]
What? :smile:

**Comment by Sharlaan** [comment]
Maybe something like this ?
```
static defaultProps = {
    ...
    filter: AutoComplete.caseInsensitiveFilter,
    ...
}
```

**Comment by leMaik** [comment]
The filter needs to match every value if the input is empty so that the dropdown menu opens automatically on focus. The default filters of `AutoComplete` don't do this. That's why we have to provide our own default filter.

**Comment by leMaik** [comment]
@Sharlaan Re-using `AutoComplete`s filters sounds good to me. I'll change the way the auto-open feature works (and resolve this issue while I'm on it). :+1:

**Comment by Sharlaan** [comment]
Thanks but my current tests seem to show the filter property doesnot take any provided function:
```
<ChipInput
  filter={(search, key) => search === '' || key.toLowerCase().includes(search.toLowerCase())}
/>
```

... still gives caseSensistive behavior while should be insensitive.

**Comment by leMaik** [comment]
@Sharlaan I'm currently fixing that. :+1:

**Comment by Sharlaan** [comment]
Impressive answer speed  👍

**Comment by leMaik** [comment]
This works now:
```jsx
<ChipInput
  openOnFocus
  filter={AutoComplete.fuzzyFilter}
  dataSource={['alpha', 'beta']}
  hintText="Try typing apha..." //sic!
/>
```

**Comment by Sharlaan** [comment]
Great job, default caseInsensitive works perfect !

but... filter={AutoComplete.fuzzyFilter} means user has to import { AutoComplete } from 'material-ui' on top of importing material-chip-input....

That's why i suggested the enum in Issue #18 .

**Comment by leMaik** [comment]
@Sharlaan I won't add any filter in this component. Importing `AutoComplete` adds no overhead at all, as this component also uses `AutoComplete`.

**Comment by Sharlaan** [comment]
```
import React from 'react'
import { AutoComplete } from 'material-ui'
import ChipInput from 'material-chip-input'

const Container = (props) => {
  return (
    <ChipInput filter={AutoComplete.fuzzyFilter} />
  )
}
```

compared to:
```
import React from 'react'
import ChipInput from 'material-chip-input'

const Container = (props) => {
  return (
    <ChipInput filter={'fuzzyFilter'} />
  )
}
```

**Comment by leMaik** [comment]
Wow, that's one line in your code vs. more code I have to maintain. :-1: I'm still not convinced.

**Comment by Sharlaan** [comment]
true it's more typing for you, i just meant AutoComplete reference should be purely internal.

**Comment by leMaik** [comment]
Oh, I see what you mean. You don't want to depend on `AutoComplete` because it's just an implementation detail? Just think of the `filter` function as of _any_ function, where `AutoComplete.fuzzyFilter` (and the other functions) fortunately have the same interface and thus can be used. :)

**Comment by Sharlaan** [comment]
Ok got it, sorry i didnot realize the "single interface for any filter function" pattern.
Fine with that.
