### ISSUE TITLE
Rejected chip gets added to the next valid chip

### ISSUE THREAD

**Issue by alexcroox** [TeamWertarbyte/material-ui-chip-input#171]
I'm using the following validation on input

```
onBeforeRequestAdd (email) {
    return hasAmpersat(email)
}
```

and

```
ChipInput
    floatingLabelText="Email addresses"
    fullWidth
    value={this.state.emails}
    newChipKeyCodes={[13, 188, 32]}
    onBeforeRequestAdd={(email) => this.onBeforeRequestAdd(email)}
    onRequestAdd={(email) => this.onRequestAdd(email)}
    onRequestDelete={(deletedEmail) => this.onRequestDelete(deletedEmail)}
/>
```

And if I type something that isn't an email it doesn't "chip" it, it does however add it to the next vaild email when I press a newChipKeyCode. How would you recommend I approach this?

![gif](https://cl.ly/oSdO/Screen%20Recording%202017-12-20%20at%2008.25%20pm.gif)

**Comment by leMaik** [comment]
This is the intended behavior. If `onRequestAdd` returns `false`, the input is _not_ cleared and the chip is _not_ added.

You can, however, remove the `onBeforeRequestAdd` handler and just not add the chip in the `onRequestAdd` handler if it is an invalid email address. That should do what you intend to do. :wink:

**Comment by alexcroox** [comment]
Ah that makes perfect sense, thank you!
