### ISSUE TITLE
Customize autocomplete MenuItem

### ISSUE THREAD

**Issue by darkchaplain** [TeamWertarbyte/material-ui-chip-input#172]
I'm trying to customize `MenuItem` as it's described in http://www.material-ui.com/#/components/auto-complete.
Here is the code: 
```
import React from 'react';
import ChipInput from 'material-ui-chip-input';
import { MenuItem } from 'material-ui';

const CategoryTags = () => {
  const dataSource = [
    {
      text: 'text-value1',
      value: (
        <MenuItem
          primaryText='text-value1'
          secondaryText='&#9786;'
        />
      ),
    },
    {
      text: 'text-value2',
      value: (
        <MenuItem
          primaryText='text-value2'
          secondaryText='&#9786;'
        />
      ),
    },
  ];

  return (
    <div>
      <ChipInput
        fullWidth
        hintText='Categories'
        openOnFocus
        dataSource={dataSource}
      />
    </div>
  );
};

export default CategoryTags;
```
I can see customized menu items when I type something:
<img width="604" alt="screen shot 2017-12-27 at 5 14 38 pm" src="https://user-images.githubusercontent.com/7280838/34385175-8931998a-eb29-11e7-8a3a-776767383f44.png">
But I get an error when I choose menu item:
```
Uncaught TypeError: chip.trim is not a function
    at ChipInput.handleAddChip (bundle.js:96683)
    at Object.onAutocompleteItemClick [as onItemClick] (bundle.js:96581)
    at Menu.handleMenuItemClick (bundle.js:7367)
    at Object.onClick (bundle.js:7269)
    at Object.ListItem._this.handleClick [as onClick] (bundle.js:10284)
    at EnhancedButton._this.handleClick (bundle.js:1160)
    at HTMLUnknownElement.callCallback (bundle.js:40398)
    at Object.invokeGuardedCallbackDev (bundle.js:40437)
    at Object.invokeGuardedCallback (bundle.js:40294)
    at Object.invokeGuardedCallbackAndCatchFirstError (bundle.js:40308)
```
`material-ui-chip-input` version is 0.18.4
`material-ui` version is 0.20.0

Can I get help on this issue please?

**Comment by leMaik** [comment]
At the moment, it's not possible to customize the `MenuItem`s for this component. It would be a great feature, though! :+1:

We should add a `autoCompleteItemRenderer` that creates a `MenuItem` from a value. Would you like to start a PR that does that?

**Comment by darkchaplain** [comment]
I will try to have a look at code and make PR

**Comment by leMaik** [comment]
@darkchaplain Awesome! :tada:

**Comment by darkchaplain** [comment]
I made an investigation, creating new property does not make sense, because the only way to customize menu item is to modify datasource. I'm going to create PR with solution

**Comment by darkchaplain** [comment]
@leMaik Could you have a look at PR please and give a feedback?

**Comment by leMaik** [comment]
@darkchaplain 

> because the only way to customize menu item is to modify datasource

But a better way to customize the menu items would be to _customize the menu items_ by adding a callback that can do that.

**Comment by darkchaplain** [comment]
@leMaik it will be natural way like it's described in http://www.material-ui.com/#/components/auto-complete . But I will not complain and will remake, thanks for response.

**Comment by darkchaplain** [comment]
@leMaik "Additionally, most other properties of Material UI's Auto Complete and Text Field should be supported. Please open an issue if something is missing or does not work as expected."

**Comment by leMaik** [comment]
@darkchaplain Oh, _now_ I get what the PR does. :thinking: We currently don't handle non-string `dataSource` values properly which prevents you from customizing it like you can do in `AutoComplete`. Stupid me.

**Comment by darkchaplain** [comment]
@leMaik And if my PR will be accepted, could I ask you to make release as soon as possible, please?

**Comment by leMaik** [comment]
@darkchaplain I always try to publish a new release right after something is fixed. :+1:
