### ISSUE TITLE
Add option to Text as Chip on blur event

### ISSUE THREAD

**Issue by quorak** [TeamWertarbyte/material-ui-chip-input#174]
Hey there, thanks for the great component.
We have the Issue, that people use the Chip component as they would use a TextField in the beginning.
Thus they write something in the textfield and than click into the next textfield. This makes the entered text dissapear instead adding it as a Chip. Even when we have clearOnBlur set to false, the behaviour is not as expected.

We would suggest to add a boolean option addOnBlur, which would add the Text as Chip on blur Event.

**Comment by leMaik** [comment]
@quorak Thanks a lot for the PR! :tada: The idea is fine, but maybe we should introduce a `blurBehavior` prop and deprecate `clearOnBlur` instead. I.e. `blurBehavior='clear'` and `blurBehavior='add'` :thinking:

**Comment by quorak** [comment]
will add this to the next branch

**Comment by gknapp** [comment]
Until this PR is raised and merged, how can this be implemented in `onBlur`?

**Comment by leMaik** [comment]
I don't know why I didn't close this, but this feature is included since v1.0.0-beta.5
