### ISSUE TITLE
Warning raised while using onUpdateInput (next branch)

### ISSUE THREAD

**Issue by karthikmurugadoss** [TeamWertarbyte/material-ui-chip-input#178]
I received the following warning message while using onUpdateInput.
```
Warning: Unknown prop `onUpdateInput` on <div> tag. Remove this prop from the element
```
Is this perhaps because onUpdateInput is not specified in ```this.props``` at https://github.com/TeamWertarbyte/material-ui-chip-input/blob/next/src/ChipInput.js#L379?

**Comment by leMaik** [comment]
Thank you! :+1: I added a test for this (that ensures that no warning pops up and `onUpdateInput` works properly. Should never happen again.
