### ISSUE TITLE
filters enum

### ISSUE THREAD

**Issue by Sharlaan** [TeamWertarbyte/material-ui-chip-input#18]
How about exposing an enum for available filters ?

filters property would have specifications:
```
function | enum('caseInsensitive', 'caseSensitive', 'fuzzy')
default: 'caseInsensitive'
```

I think the underlying <AutoComplete/> already provides those 3 filters functions (and another one called levenshteinDistance i don't understand its behavior...).

**Comment by leMaik** [comment]
This is out of the scope of this project. You can define your own filter when using this component with the `filter` prop and do any magic stuff you like. :wink:
