### ISSUE TITLE
Chips added with custom chipRendered added below

### ISSUE THREAD

**Issue by anjuschi** [TeamWertarbyte/material-ui-chip-input#180]
I am using the next version that is being ported to Material-ui 1.0.0 beta. I noticed that when I pass a chipRenderer, the new chips are being added below the existing instead of on the same line as the existing. If the remove the chipRenderer then the chip are added on the same line. 
Any suggestions?

Furthermore, the reason I am using a chipRenderer is because without it, the ChipInput in creating Basic Chips i.e. without the (X) delete. So by added a chipRenderer and specifying a 'onRequestDelete' function, I get Chips with (X).
Thanks.

**Comment by leMaik** [comment]
Sounds like some styles are missing from your custom chips. Could you please show your custom renderer?

**Comment by anjuschi** [comment]
Below is the code for the ChipInput including the custom renderer. The only style I have added is a top margin since the chips were sticking to each other. 

 <ChipInput
              value={this.state.receivers}
              onAdd={this.onChangeReceivers}
              onDelete={this.onDeleteReceiver}
              onBlur={this.onBlurReceiver}
              newChipKeyCodes={[13, 188, 9]}
              placeholder={message.notifications.RECEIVERS_HINT_TEXT}
              helperText={error ? ' ' : null}
              disableUnderline
              style={{
                width: 460,
              }}
              chipRenderer={({ value, handleDelete}) => (
                <Chip
                  onRequestDelete={handleDelete}
                  label={value}
                  style={{
                    margin: '2px 0 0 0',
                  }}
                />
              )}
            />

**Comment by anjuschi** [comment]
I installed the latest version of your library and it works now! Thanks.
