### ISSUE TITLE
Uncontrolled objects as chips - empty value

### ISSUE THREAD

**Issue by orm109** [TeamWertarbyte/material-ui-chip-input#181]
Hey all and thanks for this component

The thing is that in case of uncontrolled objects as chips, empty string is allowed
if you press "Enter" without any text you will get a new chip with an empty string

see this [storybook](https://teamwertarbyte.github.io/material-ui-chip-input/?selectedKind=ChipInput&selectedStory=objects%20as%20chips%2C%20uncontrolled&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel)

**Comment by leMaik** [comment]
Thanks for reporting this bug. I'll try to fix it soon.

**Comment by orm109** [comment]
https://github.com/TeamWertarbyte/material-ui-chip-input/pull/182
what do you say ?

**Comment by leMaik** [comment]
@orm109 Thanks a lot! :+1:

**Comment by leMaik** [comment]
A wild v0.18.6 appeared! https://github.com/TeamWertarbyte/material-ui-chip-input/releases/tag/v0.18.6
