### ISSUE TITLE
Cannot change Chip style 

### ISSUE THREAD

**Issue by orm109** [TeamWertarbyte/material-ui-chip-input#184]
should have the option by a prop to change the Chip style, similar to `chipContainerStyle`

**Comment by leMaik** [comment]
Thanks for raising this and for the PR! :tada: 
I'll not merge it, though. This can already be done by implementing a custom `chipRenderer`.

**Comment by leMaik** [comment]
There is even an example with custom chip styles: https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/stories/index.js#L104 :disappointed:
