### ISSUE TITLE
chipRenderer: isFocused is bad when using dataSourceConfig

### ISSUE THREAD

**Issue by orm109** [TeamWertarbyte/material-ui-chip-input#186]
`isFocused` should be using for coloring the Chip

see [storybook](https://teamwertarbyte.github.io/material-ui-chip-input/?selectedKind=ChipInput&selectedStory=objects%20as%20chips%2C%20uncontrolled&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel)

something is bad with the logic here:
```
isFocused: dataSourceConfig ?
(this.state.focusedChip && this.state.focusedChip[dataSourceConfig.value] === value) :
(this.state.focusedChip === value),
```

**Comment by orm109** [comment]
`focusedChip` is a value and not an object

**Comment by leMaik** [comment]
Good one! :+1: Would you mind checking this on the `next` branch and maybe submit a PR there, too?

**Comment by orm109** [comment]
i will do it later
how about adding to storybook ?

**Comment by orm109** [comment]
@leMaik the issue does not appear in `next`

seems like this one work well
```
isFocused: this.state.focusedChip === i
```

**Comment by orm109** [comment]
when do you think to have `next` into `master`?

**Comment by leMaik** [comment]
In all of our material-ui-related projects, `next` is the port for material-ui 1.0.0-beta. It will be merged into `master` when material-ui 1.0.0 becomes stable. The current `master` branch will then be renamed to `legacy`.

**Comment by orm109** [comment]
Ok
What else is needed in order to merge this one ?

**Comment by leMaik** [comment]
@orm109 There you go: https://github.com/TeamWertarbyte/material-ui-chip-input/releases/tag/v0.18.7
