### ISSUE TITLE
Custom onNewRequest function property from Autocomplete is not called

### ISSUE THREAD

**Issue by nabiltntn** [TeamWertarbyte/material-ui-chip-input#189]
I wanted to add `onNewRequest` to add custom behavior when adding item from Autocomplete but the function  was not fired.
```js
<ChipInput
  ...
  onNewRequest={this.handleOnNewRequest}
/>



```
**Versions :** 
"material-ui": "^0.19.4",
"material-ui-chip-input": "^0.18.7",

**Comment by leMaik** [comment]
If you want some custom behavior when adding an item, use `onRequestAdd` or `onChange`.

> Callback function that is fired when a list item is selected, or enter is pressed in the TextField.

Since we _add_ the value to the chip input when enter is pressed or a list item is selected, overriding `onNewRequest` is not really useful anyway.
