### ISSUE TITLE
Question: How to handle selecting only chips from the dataSource?

### ISSUE THREAD

**Issue by johnandblue** [TeamWertarbyte/material-ui-chip-input#195]
In my case I need the user to only be able to select items from the `dataSource`, so he cannot add new chips when he types.
Is there any way of handling that issue?

Thanks!

**Comment by leMaik** [comment]
It's not yet possible to only allow adding items from the dataSource (PR welcome!) but you could prevent items that don't come from the dataSource in `onBeforeRequestAdd`.

**Comment by johnandblue** [comment]
I'll try to make it work with `onBeforeRequestAdd`, thanks! (and I'll put in my TODOs the PR if I make it work 😉 )
Also I was looking for the source code that you're using in the storybook, to look at the examples, as they would be really useful, but I couldn't find the repo. would it be possible to share the link? 

Thanks again!

**Comment by leMaik** [comment]
Glad I could help. Feel free to re-open this issue (or create a new one) if you have further questions.
