### ISSUE TITLE
Question: How to reference a ChipInput when using onChange?

### ISSUE THREAD

**Issue by johnandblue** [TeamWertarbyte/material-ui-chip-input#196]
lets say that I have several `ChipInputs` and all of them use a similar `handleFunction` when `onChange`, but I need to know the name of the `ChipInput`. the idea would be doing something like we can do in a material-ui TextField, but with the chips.
```js
  handleChangeInput = (e) => {
    this.setState({
      [e.target.name]: e.target.value,
    });
  }
```
I get `onChange` only passes the `chips` as parameter? or there is any other way to reference the `ChipInput` that is being triggered?

Thanks!

**Comment by leMaik** [comment]
:thinking: Use a different handler function for every chip input. Or maybe wrap the chip input so that you can add a name to it. At the moment, since the event doesn't come from the chip input but the underlying text field, `e.target.name` wouldn't really contain anything useful.

**Comment by johnandblue** [comment]
Yep, I considered both cases. It's just I'm working in a form that contains 60 fields... so imagine creating 60 handle functions every time the component is  created... 😥...
I guess best solution is wrap the `ChipInput` and pass and identifier as a parameter alongside the cb

**Comment by leMaik** [comment]
Wrapping existing components is really helpful to get shorter code. :+1: 

E.g. like this

```
function NamedChipInput ({ onChange, name, ...other }) {
  return (
    <ChipInput onChange={(...args) => onChange(name, ...args)} {...other} />
  )
}
```

**Comment by johnandblue** [comment]
Yup! thanks a lot ;)
