### ISSUE TITLE
Does not work with mobile keyboards that have no Enter key

### ISSUE THREAD

**Issue by ohansrud** [TeamWertarbyte/material-ui-chip-input#198]
The following code works on desktop version, but not when I open the page on my android phone:

                        <ChipInput
                          errorText={null}
                          value={myValue}
                          floatingLabelText="Something"
                          onRequestAdd={(chip) => this.addChips(chip, n)}
                          onRequestDelete={(chip, index) => this.removeChips(chip, n, index)}
                        />

On desktop I can add a new chip with the Enter key.
The Samsung keyboard however, does not display Enter key, but a Next key that skips to the next input field. 
Hence, the field gets cleared.
Any workaround to make this work on mobile?

**Comment by leMaik** [comment]
It works fine on mobile, seems to be an issue with your particular keyboard. You can use the `newChipKeyCodes` prop to specify other key codes that should create a new chip. E.g. you can create a new chip when pressing space.

**Comment by leMaik** [comment]
I'll close this as a work-around is described above and fixing bad mobile keyboards is a bit out of scope.

**Comment by leMaik** [comment]
@robsdedude You could use space for adding new chips. That said, the Android on-screen keyboard seems to suck. Regarding market share: Not every Android phone uses the same keyboard.
PRs regarding textInput welcome. :+1:

**Comment by robsdedude** [comment]
Another idea that comes to my mind is an option to add a + IconButton or so to the right of the input that, when clicked/touched, adds a new chip. So that you don't have to rely on the keyboard capabilities at all.

**Comment by robsdedude** [comment]
Despite the button idea it could also be worth experimenting with textarea as input (causes Android to show the enter key): https://jsfiddle.net/taditdash/b8ee0gnu/

**Comment by leMaik** [comment]
@robsdedude The second option sounds like a great workaround! :+1:

**Comment by Tamakimouto** [comment]
Sorry to dig up an old issue, but I thought I might add that you can just make a clickable submit button yourself.

```javascript
<ChipInput blurBehavior="ignore" clearInputValueOnChange inputRef={ref => this.chipInput = ref} />
<button onClick={()=> handleAddChip(this.chipInput.value)}>submit</button>
```
