### ISSUE TITLE
Long error messages aren't positioned correctly

### ISSUE THREAD

**Issue by llamamoray** [TeamWertarbyte/material-ui-chip-input#199]
Hi,

If the error message of the input is too long and overflows to another line, the control doesn't position it correctly like the material-ui TextField. 

Any ideas how to fix this?

![image](https://user-images.githubusercontent.com/2970147/39251268-c5590ae6-489a-11e8-9ef7-a9e1ee08ad42.png)

For reference, material-ui:
![image](https://user-images.githubusercontent.com/2970147/39251376-02ebe0e0-489b-11e8-9a5b-2bb13464f37a.png)

Thanks,
Alex

**Comment by leMaik** [comment]
@llamamoray Seems like something in the style of our [label](https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/src/ChipInput.js#L508) is different than in Material-UI's TextField.

If you'd like to investigate that, I'd really appreciate a PR. :+1:

**Comment by llamamoray** [comment]
Hi @leMaik - fix in PR #204 

If you're happy with that I'd very much appreciate if this could be published asap :)

**Comment by leMaik** [comment]
@llamamoray [v0.18.8](https://github.com/TeamWertarbyte/material-ui-chip-input/releases/tag/v0.18.8) is out now, thank you! :+1:
