### ISSUE TITLE
Chip editing

### ISSUE THREAD

**Issue by leMaik** [TeamWertarbyte/material-ui-chip-input#2]
I don't know if this is useful, but at least Angular Material supports editing existing chips.

**Comment by acomito** [comment]
Can't hurt. I'd use it.

**Comment by ashl1** [comment]
I vote not to realize this as:
1. Google Material Design doesn't tell about this behavior
2. Editing chips is not user-friendly UX pattern, because user only see delete button on the chip and easily understand that can delete and add new chip. Editing the chip breaks the logic and make it more sophisticated to user.
3. Chips may be used like a button, when clicking on chips will display full info or smth. Click to edit breaks this behavior too.

**Comment by ashl1** [comment]
And of course, we as the programmers are able to implement any we want, but Material Design was developed by UX designers, which may includes many AB-testing and focus groups testing. We shouldn't add new functionality based on our first thought.

**Comment by leMaik** [comment]
Totally  agree with @ashl1. Actually, it's as easy to delete a chip and add a new one as it is to edit one for the user. Right now, chips can't be used like buttons, though.

**Comment by ashl1** [comment]
> Right now, chips can't be used like buttons, though.

I know. I talked about Google Material Design specification:

> Touching a chip opens a full detailed view (either in a card or full screen) or a menu of options related to that chip.
https://material.google.com/components/chips.html#chips-behavior

**Comment by leMaik** [comment]
That sounds like a neat feature for later. At least I could add a prop to customize the chip element.

**Comment by acomito** [comment]
fair argument from IeMaik.

I have a use case where I'm adding emails. Some sort of validation hook may be nice. I'm not sure if the usual type="email" will do anything. I didn't get to testing it out.

**Comment by leMaik** [comment]
@acomito Do you want to validate the input while the user is typing or when the user adds a tag? The latter would be possible in controlled mode (you could show a Snackbar to notify the user about an invalid e-mail adress).
Validation while typing sounds pretty cool and it is already possible to handle input changes using the `onUpdateInput` callback and perform validaton. Error texts are not yet supported, but I don't know how to show that the chip the user is about to add should be highlighted as invalid. I believe that using the default error text would suggest that all chips are invalid. Do you have any suggestions on this?

**Comment by acomito** [comment]
I'm planning to dig into it tomorrow, so I'll report back. I'm not sure if it is possible (or would make sense) to wrap/integrate into fromsy-material-ui. But I'll check back in tomorrow with better feedback. Thanks for the notes on the current possibilities.

**Comment by leMaik** [comment]
@acomito Integrating this with formsy-react is pretty straightforward, we do this in another project.

```jsx
import * as React from 'react'
import Formsy from 'formsy-react'
import { AutoComplete } from 'material-ui'
import ChipInput from 'material-ui-chip-input'

const styles = {
  chip: {
    margin: 4
  },
  wrapper: {
    display: 'flex',
    flexWrap: 'wrap'
  }
}

export const FormsyTags = React.createClass({
  mixins: [Formsy.Mixin],

  getInitialState() {
    return {
      value: []
    }
  },

  componentWillMount() {
    this.setValue(this.props.defaultValue || this.props.value || [])
    this.setState({
      value: this.props.defaultValue || this.props.value || []
    })
  },

  handleNewRequest(chosenRequest, index) {
    const newData = this.getValue()
    chosenRequest.split(',').map((t) => t.trim()).filter((t) => t.length > 0).forEach((tag) => {
      if (!this.props.isReadOnly || (this.props.isReadOnly && index > -1)) {
        if (newData.indexOf(tag) < 0) {
          newData.push(tag)
          this.setState({
            value: newData,
            searchText: ''
          })
          this.setValue(newData)
        }
      }
    })
  },

  handleChange(newData) {
    this.setValue(newData)
  },

  render() {
    const FormsyTags = this.showRequired() ? 'required' : this.showError() ? 'error' : null

    const errorMessage = this.getErrorMessage()

    return (
      <div className={FormsyTags}>
        <ChipInput
          hintText={this.props.hintText}
          floatingLabelText={this.props.floatingLabelText}
          filter={AutoComplete.caseInsensitiveFilter}
          dataSource={this.props.dataSource || []}
          maxSearchResults={3}
          onNewRequest={(chosenRequest, index) => this.handleNewRequest(chosenRequest, index)}
          onUpdateInput={this.handleNewTagChange}
          defaultValue={this.state.value}
          onChange={(chips) => this.handleChange(chips)}
          style={{ width: '100%' }}
        />
        <span>{errorMessage}</span>
      </div>
    )
  }
})
```

**Comment by ashl1** [comment]
@leMaik I think we should add this as an example in storybook. And sohuld think about collaboration with [formsy-material-ui](https://github.com/mbrookes/formsy-material-ui)

**Comment by leMaik** [comment]
@ashl1 I agree that we should add this as an example.

Regarding formsy-material-ui: This project's (chip-input) scope is to provide a chip input, as a re-usable component that has no further dependencies than react and material-ui. Thus, I wouldn't like to include a formsy component in this repository, but it would be a cool thing for another project. I don't know if the guys over at formsy-material-ui would like add this, so that we don't need a separate formsy-material-chip-input project. I opened [an issue over there to discuss this](https://github.com/mbrookes/formsy-material-ui/issues/138).

**Comment by leMaik** [comment]
Since chip editing won't be added, I'll close this issue.
@acomito If you have any issues integrating this with Formsy, please feel free to open a new ticket.

**Comment by MrLoh** [comment]
@leMaik I'm trying to use the chip input inside formsy, but can't quite get it to work. Could you provide an example how to use it?

**Comment by leMaik** [comment]
@MrLoh I already provided an example, [right in this issue](https://github.com/TeamWertarbyte/material-ui-chip-input/issues/2#issuecomment-247402164). :wink: 
Feel free to open a new issue and provide some more details, I'd be happy to help you!

**Comment by ashl1** [comment]
@leMaik Have you opened a PR to add your example in public examples?

**Comment by leMaik** [comment]
@ashl1 No I didn't, but I also don't use formsy-material-ui.
