### ISSUE TITLE
Placeholder is not displayed entirely when fullWidth is enabled

### ISSUE THREAD

**Issue by ugomeda** [TeamWertarbyte/material-ui-chip-input#200]
In version 1.0.0-beta4, with this code :

```
<ChipInput
  fullWidth
  placeholder="Ajouter des utilisateurs au groupe"
/>
```

The placeholder is cut :

![screenshot from 2018-04-26 10-27-42](https://user-images.githubusercontent.com/932339/39294837-0bfe4fe0-493d-11e8-918f-cf1aeb43d07f.png)

**Comment by leMaik** [comment]
This is due to us using the placeholder of the input element (which doesn't fill the entire width by design). We'll have to see how we can fix this.

**Comment by fabriziocucci** [comment]
Is there a temporary workaround for this?

**Comment by leMaik** [comment]
@fabriziocucci No, but I'd appreciate a PR that permanently fixes this. :+1:

**Comment by trylimits** [comment]
It seems like that this issue does not only affect the placeholder, but long inputs in general.
The following workaround fixes both issues this for me:

```
const styles = theme => ({
    chipContainer: {
        display: 'flex',
        flexFlow: 'row wrap'
    },
    inputRoot: {
        flex: '1 0 auto'
    }
});

[...]

<ChipInput
  classes={{
    chipContainer : classes.chipContainer,
    inputRoot : classes.inputRoot
  }}
  fullWidth
/>

```
