### ISSUE TITLE
Unable to scroll through autocomplete when there's more data than can fit on the screen

### ISSUE THREAD

**Issue by ncanning** [TeamWertarbyte/material-ui-chip-input#201]
If you have a lot of data in your autocomplete data source, there isn't a way to scroll through the options:

![noscrollchipinput](https://user-images.githubusercontent.com/6805216/39387610-5792b12e-4a2f-11e8-8533-347eb151e4d8.gif)

This is a pretty easy fix, though. The `AutoComplete` component has a `listStyle` prop, which you can give a `maxHeight` and `overFlow: 'auto'`, which solves the issue:

![scrollchipinput](https://user-images.githubusercontent.com/6805216/39387962-9a39d0dc-4a31-11e8-8288-81c3d661704c.gif)

**Comment by leMaik** [comment]
@ncanning Thanks for reporting this. Maybe we can set a reasonable default `maxHeight`, e.g. 300px, to fix this. Would you like to submit a PR? :+1:

**Comment by ncanning** [comment]
Sure, no problem. I should be able to get one out today.

**Comment by ncanning** [comment]
https://github.com/TeamWertarbyte/material-ui-chip-input/pull/202

**Comment by leMaik** [comment]
For future readers: https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/stories/index.js#L76
