### ISSUE TITLE
Please export the defaultChipRenderer

### ISSUE THREAD

**Issue by frenya** [TeamWertarbyte/material-ui-chip-input#206]
Hello,

would it be possible to export the `defaultChipRenderer` function in `ChipInput.js`? It would allow for easier customisation of chips in special cases.

Example use case: Make the first chip non-deletable

```javascript
const chipRenderer = ({ handleRequestDelete, ...otherProps }, key) => (
  defaultChipRenderer({
    handleRequestDelete: key ? handleRequestDelete : null
    ...otherProps
  }, key)
);
```

Currently, I need to fully replicate the `defaultChipRenderer` including styles, colors etc. to be consistent. Exporting the renderer would make life much easier.

Pretty please :)

Frank

P.S. I could make a pull request, but it's really just adding the "export" keyword.

**Comment by leMaik** [comment]
@frenya It sounds like a great first PR anyway. :+1:

**Comment by frenya** [comment]
If you insist ... 😄 

https://github.com/TeamWertarbyte/material-ui-chip-input/pull/207

**Comment by leMaik** [comment]
@frenya Thank you, I'll cherry-pick that so that you don't have to submit a new PR for the next branch. :wink:

**Comment by frenya** [comment]
Thanks 👍

**Comment by leMaik** [comment]
@frenya v0.19.0 (one added keyword caused a minor version bump :D) will be releases in a few minutes
