### ISSUE TITLE
Support for theme overrides ?

### ISSUE THREAD

**Issue by nsaubi** [TeamWertarbyte/material-ui-chip-input#208]
Version : 1.0.0-beta.4

I can't override the chipContainer element in the theme. Don't know if I'm missing something or if functionnality is missing...

```
const theme = createMuiTheme({
  overrides: {
    ChipInput: {
      chipContainer: {
        backgroundColor: '#e0e0e0'
      }
    }
  }
});
```
not working.

**Comment by leMaik** [comment]
It's not possible to customize our components from within the theme. Use the `classes` property instead.
