### ISSUE TITLE
Q.v1. Support {shrink: true} for label ?

### ISSUE THREAD

**Issue by nsaubi** [TeamWertarbyte/material-ui-chip-input#209]
Version : 1.0.0-beta.4

Hi,
is it possible to do the same as a TextField element, meaning adding the property `InputLabelProps: { shrink: true }` ?
I would like my label to always float, even if empty.

Thanks

**Comment by leMaik** [comment]
This is possible by specifying `InputLabelProps={{ shrink: true }}`
