### ISSUE TITLE
How to integrate in redux-form

### ISSUE THREAD

**Issue by gontard** [TeamWertarbyte/material-ui-chip-input#21]
Hello,

i am trying to integrate your component with [redux-form](https://github.com/erikras/redux-form).
I wrote 

`<Field name="myField" component={ChipInput} hintText='...' />`

but the field the edited values are not linked with the redux-form state.
Any suggestion ?

**Comment by leMaik** [comment]
Please take a look at [http://redux-form.com/6.0.5/examples/material-ui/](these examples). It looks like you need to write some kind of `renderChipInput` function that connects this component and the `Field`. Sounds like a good new project for you. :)

**Comment by gontard** [comment]
Thanks for the hint.

I found this solution. It works but i am really not sure if it is the right way to do it.

```
const renderChip = ({input, hintText, floatingLabelText}) => (
  <ChipInput
    {...input}
    value = { input.value || []}
    onRequestAdd={(addedChip) => {
      let values = input.value || [];
      values = values.slice();
      values.push(addedChip);
      input.onChange(values);
    }}
    onRequestDelete={(deletedChip) => {
      let values = input.value || [];
      values = values.filter(v => v !== deletedChip);
      input.onChange(values);
    }}
    onBlur={() => input.onBlur()}
    hintText={hintText}
    floatingLabelText={floatingLabelText}
  />
);
```

and i use the function in a redux-form field:

`        <Field
          name="myValue"
          component={ renderChip }
          hintText='...'
          floatingLabelText='Value'
        />`

Now, i have a new problem, the style is not applied to the Chip:

![capture d ecran 2016-10-05 a 14 47 29](https://cloud.githubusercontent.com/assets/1221664/19113616/dbd81e0a-8b0a-11e6-91e0-843ebfc17ccb.png)

**Comment by leMaik** [comment]
:open_mouth: Does your CSS overwrite any of the chip's default styles?

**Comment by gontard** [comment]
You were right 👍 

The style came from by this rule in the `normalize.css`. 

````
button,
html [type="button"], /* 1 */
[type="reset"],
[type="submit"] {
  -webkit-appearance: button; /* 2 */
}

```

Thanks again.

**Comment by pvjones** [comment]
Thanks so much for posting this! You saved my life!

**Comment by yoihito** [comment]
@pvjones How do you use ChipInput with redux-form? I tried the wrapper above. Redux-form hangs and dispatches endless REGISTER_FIELD actions.

**Comment by DanielArthurUK** [comment]
@pvjones `REGISTER_FIELD` actions are only dispatched for each field in your form. It sounds like you're stuck in some kind of render loop 🤔
