### ISSUE TITLE
Add and array with 2 elements

### ISSUE THREAD

**Issue by juanriglos** [TeamWertarbyte/material-ui-chip-input#212]
Hello, i want to add an element with 2 inputs, here i select an option and it add to the array, but what i need is to select an option and add a measure to that option is that possible?. The idea es select and option and a quantity and then add to the chip.

Thank you

**Comment by leMaik** [comment]
That's not possible and there are no plans to implement it as it's a pretty big change. Feel free to fork this project, though. It should be a good base to start on. 👍
