### ISSUE TITLE
Bring back auto-complete

### ISSUE THREAD

**Issue by 009800** [TeamWertarbyte/material-ui-chip-input#214]
React does not recognize the `hintText`

I'm getting this error. And then I had a look to the ChipInput.js and there was no implementation for hintText. The auto complete is not working as well.

Matierl-ui 1.0.0 and material-ui-chip-input@next

Do I miss something? 

Edit: Sorry I just saw it has changed to `helperText`. But the autocomplete is still not working. (I'm using dataSource={['alpha', 'beta']} )

**Comment by leMaik** [comment]
I need more information than "is still not working" to help you. Would you please show a bit of your code? :wink:

**Comment by leMaik** [comment]
Unfortunately,aAuto-complete is not yet implemented. See #88 and #192 for an example on how to integrate react-autosuggest with material-ui-chip-input.

In the future, we'd love to have examples on how to use various auto-suggestion libraries. PRs welcome! :tada:

**Comment by leMaik** [comment]
Sorry, I was a bit fast with closing this. :confused:

**Comment by vincentbouillart** [comment]
https://material-ui.com/demos/autocomplete/ ?

**Comment by leMaik** [comment]
Now that the PR is finally merged, I think this can be closed. :sunglasses: The example can be found [here](https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/stories/examples/react-autosuggest.js)
