### ISSUE TITLE
Are there any built in functionality for Clear/Delete All Chips?

### ISSUE THREAD

**Issue by lstr168** [TeamWertarbyte/material-ui-chip-input#215]
Hi, guys maybe you could help me!

I was looking for something to Clear/Delete all Chips functionality  (x in the end of the TextField or something like that).

All I found was this one
https://github.com/TeamWertarbyte/material-ui-chip-input/issues/43

So my question is are some there build-in functionality for that?
Thank you

**Comment by leMaik** [comment]
Hi, there is no built-in functionality to do so and we won't add them. Please use controlled mode to control the chips, as shown in the issue you linked. https://github.com/TeamWertarbyte/material-ui-chip-input/issues/43#issuecomment-261705304

**Comment by leMaik** [comment]
Whoops, I was a bit quick to close this. Feel free to comment on this if you need further help.

**Comment by lstr168** [comment]
Hi @leMaik, thank you for the fast answer.
May I ask what's the reason you wouldn't add this functionality?
I think it is a very useful one and also 
Regarts

**Comment by leMaik** [comment]
It's _very_ un-React-y. :wink: The react way is to control components from outside, by using a `value` and a `onChange` prop. While I agree that clearing all chips is a pretty useful thing, it's also trivial to implement on your side and using a controlled component is much more flexible.

Imagine someone wants to remove all chips that start with 'A'. Easy thing to do with a controlled component; but it shouldn't be added to the chip input because not everybody needs it.

**Comment by lstr168** [comment]
I'm not a react pro but I think a trailing icon and handle the click event is how I would do it in react. 

Is there a way to add a trailing icon?

**Comment by leMaik** [comment]
Yes, just add an `IconButton` next to the chip input.

**Comment by lstr168** [comment]
I think to add it to the endAdornment is better
<ChipInput
                                value={this.state[property.PropertyName]}
                                onRequestAdd={this.handleChange(property)}
                                onRequestDelete={this.handleChange(property, true)}
                                endAdornment={
                                    <IconButton
                                        color="inherit"
                                        aria-label="open drawer"
                                        onClick={() => { this.setState({ [property.PropertyName]: [] }) }}>
                                        <Clear />
                                    </IconButton>
                                }
                            />

**Comment by nazik5** [comment]
> I think add it to the endAdornment is better
> 
> ```
> <ChipInput
>     value={this.state[property.PropertyName]}
>     onRequestAdd={this.handleChange(property)}
>     onRequestDelete={this.handleChange(property, true)}
>     endAdornment={
>         <IconButton
>             color="inherit"
>             aria-label="open drawer"
>             onClick={() => { this.setState({ [property.PropertyName]: [] }) }}>
>             <Clear />
>         </IconButton>
>     }
> />
> ```

Good idea! The only thing is I had to move `endAdornment` to `InputProps` : 
```
<ChipInput
     value={this.state[property.PropertyName]}
     onRequestAdd={this.handleChange(property)}
     onRequestDelete={this.handleChange(property, true)}
     InputProps: {{
          endAdornment={
              <IconButton
                      color="inherit"
                      aria-label="open drawer"
                      onClick={() => { this.setState({ [property.PropertyName]: [] }) }}>
                      <Clear />
            </IconButton>
         }
   }}
 />
```
