### ISSUE TITLE
Separate other props to FormControlProps and InputControlProps (call it what ever you like)

### ISSUE THREAD

**Issue by lstr168** [TeamWertarbyte/material-ui-chip-input#216]
Hi, I'd like to sugesst to separate ...other to formControlProps and inputControlProps. 
So that different properties can be applied to  this 2 components.

**Comment by leMaik** [comment]
:+1: PR welcome

**Comment by leMaik** [comment]
:scream: I just realized that `other` is _really_ bad because it is spread to _two_ components. I'll fix this ASAP!
