### ISSUE TITLE
Request: TypeScript typings

### ISSUE THREAD

**Issue by swallentin** [TeamWertarbyte/material-ui-chip-input#218]
Hi,

Thank you for providing this excellent component.

Our team would like to use this component but our project is written in TypeScript so we're wondering if there are any plans to add typings to the project?

**Comment by jannnik** [comment]
I also wondered why there are no typings for this great component. My team could provide some help if help is appreciated.

**Comment by leMaik** [comment]
We don't use TypeScript and keeping the definitions up to date is an additional effort. Feel free to submit typings though, we'll be happy to merge them. :+1:

**Comment by leMaik** [comment]
@jannnik Any help would be highly appreciated. :+1:
