### ISSUE TITLE
How to blur on every selection.

### ISSUE THREAD

**Issue by anykao** [TeamWertarbyte/material-ui-chip-input#22]
Thanks for the great work.

 I want user to select predefined items, so I'm using it by setting `openOnFocus`.
But when one selection is complete, the focus is not changing. I have to click some other where to make the popup open again.

Can I  programmingly do this in `onRequestAdd` callback.

**Comment by leMaik** [comment]
This should to the trick:
```jsx
<ChipInput
  ref={(ref) => this.chipInput = ref}
  onChange={() => this.chipInput.blur()}
/>
```

From a UX point of view, I don't think that the solution is to blur after each selection, but rather to keep the menu open, isn't it? :wink: That's not supported at the moment but is requested in #11.

**Comment by leMaik** [comment]
@anykao Did my response help you and how did you solve the issue in the meantime?

**Comment by leMaik** [comment]
Closing this after no response for over a month.
