### ISSUE TITLE
Placeholder text does not show with label shrink false

### ISSUE THREAD

**Issue by janithmalshan** [TeamWertarbyte/material-ui-chip-input#223]
While keeping input label always on top **{shrink: false}**, placeholder text does not render. It renders after click on the input field.

**Comment by leMaik** [comment]
See #209

**Comment by janithmalshan** [comment]
No, #209, does not do that

**Comment by leMaik** [comment]
@janithmalshan Sorry, I was pretty busy. I'll try to fix the open bugs shortly.

**Comment by leMaik** [comment]
This will be fixed in the next release (tomorrow). Note that to shrink the label, you need `InputLabelProps={{ shrink: true }}`
I added a unit test that verifies if this behavior works.

**Comment by janithmalshan** [comment]
Thank a lot :)
