### ISSUE TITLE
Chip label could not style

### ISSUE THREAD

**Issue by janithmalshan** [TeamWertarbyte/material-ui-chip-input#224]
I have added the ChipInput **(_1.0.0-beta.6_)** and perfectly worked with _classes_ property.
But inner text of the chip couldn't style. 

![image](https://user-images.githubusercontent.com/17025136/44506506-54203d80-a6c4-11e8-8e9d-615621fb8be4.png)

I used _label_ key to do this. 
But it does not add any styling.
```
classes={{
            label: 'testClass',
        }}
```

**Comment by janithmalshan** [comment]
Give me shout if not clear 😉

**Comment by leMaik** [comment]
@janithmalshan Please use the `chipRenderer` to customize the appearance of the chips. The storybook has an example on how to do that.
