### ISSUE TITLE
Include chip input among mui.wertarbyte.com demos?

### ISSUE THREAD

**Issue by dandv** [TeamWertarbyte/material-ui-chip-input#227]
I'm new to Wertarbyte Material-UI Components, so perhaps I'm missing something, but shouldn't this component be listed at https://mui.wertarbyte.com ?

In fact, the first paragraph on that page says,

> It already includes a lot of components, but sometimes you need a more complex composed component (e.g. a chip input or a time picker) 

But neither the chip input nor the date picker are featured in the left sidebar.

**Comment by leMaik** [comment]
We will add it for sure, this component is one of our most used ones. :sunglasses:  We need to add a styleguide for this component first, though.  This will take some time.

I don't know why our time picker is missing, though. I'll look into that next week.

**Comment by leMaik** [comment]
@dandv Time Picker is up: https://mui.wertarbyte.com/#material-ui-time-picker

**Comment by leMaik** [comment]
Done: https://mui.wertarbyte.com/#!/material-ui-chip-input
