### ISSUE TITLE
React Autosuggest example with blurBehaviour='add' is broken for clicking on suggested item

### ISSUE THREAD

**Issue by olastor** [TeamWertarbyte/material-ui-chip-input#229]
**Steps to reproduce**:

- Go to the [react autosuggestion with blur](https://teamwertarbyte.github.io/material-ui-chip-input/?selectedKind=ChipInput&selectedStory=with%20react-autosuggest%20and%20add%20on%20blur&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) example
- Enter i.e. "a"
- Click on a suggested item
- Both the input value ("a") and the selected value are added to the chip list

![screenshot_20180907_132752](https://user-images.githubusercontent.com/7479641/45216851-49f46680-b2a2-11e8-984e-d1cdb426eec8.png)

**Expected Behaviour**: Only add the clicked item (i.e. "Afghanistan")

**Comment by leMaik** [comment]
@olastor I found a solution that only affects the example and thus closed your PR. Thank you for the first fix, though. :+1:

**Comment by olastor** [comment]
@leMaik Cool. Thanks for the quick response and the fix.

**Comment by olastor** [comment]
@leMaik If I now click on a suggested item, the autocomplete does not show up when typing something afterwards (in the storybook). Can you reproduce that?

**Comment by leMaik** [comment]
@olastor Yes, I can reproduce that.

**Comment by howardlau1999** [comment]
> @leMaik If I now click on a suggested item, the autocomplete does not show up when typing something afterwards (in the storybook). Can you reproduce that?

I have the same issue

**Comment by howardlau1999** [comment]
> @olastor Yes, I can reproduce that.  I'll try to fix it soon™

Set focusInputOnSuggestionClick={true} can fix the problem on PC

**Comment by leMaik** [comment]
@howardlau1999 Thanks for the solution!

![image](https://user-images.githubusercontent.com/5544859/62009241-42110f80-b15d-11e9-9807-38580956d545.png)

I updated the example accordingly.
