### ISSUE TITLE
React autosuggest example : allowDuplicates not working ?

### ISSUE THREAD

**Issue by nsaubi** [TeamWertarbyte/material-ui-chip-input#231]
Hi,

in the react autosuggest examples, the allowDuplicates is not set (so it defaults to false). Nevertheless, the input accepts many times the same value. Is it normal ? How to prevent this ? I bet we have to implement it ourself in the handleAddChip method from Autosuggest ?

Thanks

**Comment by leMaik** [comment]
> I bet we have to implement it ourself in the handleAddChip method from Autosuggest ?

Uhm… Maybe. If you find a fix, I'd love to see a PR that fixes it. :+1:

**Comment by leMaik** [comment]
There is no such prop in react-autosuggest (anymore?): https://github.com/moroshko/react-autosuggest
