### ISSUE TITLE
Placeholder width not adapting with input field width ?

### ISSUE THREAD

**Issue by farjasju** [TeamWertarbyte/material-ui-chip-input#232]
With fullWidth set to true, it seems like the placeholder remains stuck with a fixed width, not allowing it to print entirely.
![capture](https://user-images.githubusercontent.com/39554817/45698692-de937a00-bb68-11e8-9d31-5f9773ac5552.png)

**Comment by fabriziocucci** [comment]
This is kind of a duplicated of https://github.com/TeamWertarbyte/material-ui-chip-input/issues/200.

**Comment by leMaik** [comment]
As @fabriziocucci pointed out, this is a duplicate. PRs that fix this welcome, it's not that easy, unfortunately. :disappointed:
