### ISSUE TITLE
Add support for other input "variants"

### ISSUE THREAD

**Issue by Neilpoulin** [TeamWertarbyte/material-ui-chip-input#234]
TextInputs in material-ui support variants, such as `outlined` and `filled`. Using the chips component doesn't support all of these variants, but it would be great if it did. See [here]( https://material-ui.com/demos/text-fields/#outlined) for examples. Implementation details can be found [here](https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/TextField/TextField.js)

**Comment by leMaik** [comment]
Sounds like a great improvement. :+1: A Pull Request would be highly appreciated.
