### ISSUE TITLE
New chip with ',' and ';'

### ISSUE THREAD

**Issue by lushkovsky-s** [TeamWertarbyte/material-ui-chip-input#235]
New chip creation is not working with ',' (ascii code 44) and ';' (ascii code 59) 

E.g. 
```
<ChipInput
  newChipKeyCodes=[13,32,44,59]
/>
```
Input will create chips only with enter (13) and space (32)

**Comment by leMaik** [comment]
, and ; have keyCode 188.  Unfortunately, we can't distinguish them this way. Also, keyCode is deprecated, so we should drop it and use `event.key` instead. :thinking:

**Comment by augustocardoso07** [comment]
Hi, I have a related question! How to add a new chip with space on chrome android browser? I read that all keyCode on mobile is 229!
