### ISSUE TITLE
A built in way to disable underline/inkbar. 

### ISSUE THREAD

**Issue by Tamakimouto** [TeamWertarbyte/material-ui-chip-input#238]
Material UI's Input has a disableUnderline prop that gets rid of the underline. Passing it down through InputProps doesn't do what I expected it to in this case as the Input doesn't refer to the visible input.

There should probably be a prop that disables it for ChipInput, at the very least I suggest adding `underline` and `inkbar` to the classes override docs.

**Comment by Neilpoulin** [comment]
I am pretty sure you can pass `disableUnderline` to the root component, and it will disable the underline. See the [storybook](https://teamwertarbyte.github.io/material-ui-chip-input/?selectedKind=ChipInput&selectedStory=without%20underline&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).

**Comment by Tamakimouto** [comment]
That does seem to be the case. This is something that should probably get added to the props list.
