### ISSUE TITLE
Incomplete types for props

### ISSUE THREAD

**Issue by mezzode** [TeamWertarbyte/material-ui-chip-input#239]
The TypeScript declaration file is missing some props, including `margin` and `classes`.

Any props that `ChipInput` does not explicitly take are put into `others` and are just passed on into `FormControl`, so any props that are on `FormControl` are also valid props of `ChipInput`, such as `margin`.

**Comment by leMaik** [comment]
@mezzode This is completely fixed with the latest update of your PR, right? :thinking:

**Comment by mezzode** [comment]
Yeah, should be!

**Comment by admehta01** [comment]
Why is `classes` required?
