### ISSUE TITLE
Outlined variant styling issues

### ISSUE THREAD

**Issue by mezzode** [TeamWertarbyte/material-ui-chip-input#241]
There are some style issues when using the `outlined` variant.
- `fullWidth` doesn't work. It appears to be applying `width: 100%` to the wrong node meaning that the input itself isn't full width.
- Label is not vertically aligned when using `dense` margin. With the dense margin, the label is 2px offset.

![image](https://user-images.githubusercontent.com/6572225/47252224-9085d500-d48c-11e8-912a-d6dd0d0b9c2f.png)

Currently I'm working around the issue by overriding the styles:
```ts
const styles = createStyles({
    // chipInput works around fullWidth bug with outlined variant ChipInput
    chipInput: {
        width: '100%',
    },
    // chipLabel and chipLabelShrink work around label vertical alignment bug
    // with dense margin ChipInput
    chipLabel: {
        '&:not($chipLabelShrink)': {
            top: '-2px !important',
        },
        top: '2px !important',
    },
    chipLabelShrink: {
        top: '0px !important',
    },
});
...
<ChipInput fullWidth={true} margin="dense" classes={{
    inputRoot: classes.chipInput,
    label: classes.chipLabel,
    labelShrink: classes.chipLabelShrink,
  }}
/>
```

**Comment by leMaik** [comment]
Finally fixed this. :tada:
