### ISSUE TITLE
Missing muiTheme in TypeScript + React?

### ISSUE THREAD

**Issue by rygo6** [TeamWertarbyte/material-ui-chip-input#242]
I can't figure this out. I am trying to use this component in a React + TypeScript project and I keep getting the error:

```
index.js:2178 Warning: Failed context type: The context `muiTheme` is marked as required in `ChipInput`, but its value is `undefined`.
```

I most definitely have my App wrapped in a muiThemeProvider and it is working, I am using the them many places through the app. I've tried a handful of different things, but nothing has worked and I am out of ideas. Any help appreciated.

**Comment by leMaik** [comment]
This most likely has nothing to do with TypeScript.

Which version of Material-UI and Chip Input are you using?

**Comment by buddythumbs** [comment]
I'm getting this now too.

`"@material-ui/core": "^3.2.0"`
`"material-ui-chip-input": "^1.0.0-beta.11"`

same story as above, muiTheme is provided and used extensively in other components. 

Any ideas?

**Comment by leMaik** [comment]
@buddythumbs I can't reproduce this with latest @material-ui/core :confused:
