### ISSUE TITLE
Keep placeholder after inserting values

### ISSUE THREAD

**Issue by mrmello** [TeamWertarbyte/material-ui-chip-input#252]
Hi, is it possible to keep the placeholder after entering values as shown in the first example [here](https://material.angularjs.org/latest/demo/chips) ?
From all my tries and the storybook guide, the placeholder disappears after inserting the first chip.

Thanks in advance!

**Comment by leMaik** [comment]
Great idea! :+1: Would you like to create a PR and implement this? A new prop, e.g. `alwaysShowPlaceholder` could be introduced and [this line](https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/src/ChipInput.js#L548) would need to be updated accordingly.

**Comment by mrmello** [comment]
Sure, Thanks!
