### ISSUE TITLE
Autocomplete not found

### ISSUE THREAD

**Issue by rbrilhante** [TeamWertarbyte/material-ui-chip-input#256]
ChipInput is throwing an "Can't resolve 'material-ui/AutoComplete/AutoComplete'"

material-ui-chip-input version: 0.19.0
@material-ui/core version: 3.6.0

Thanks

**Comment by leMaik** [comment]
You need to use material-ui-chip-input@latest if you are using @material-ui/core. I should really release it as v1.0.0 soon, it's been beta for quite a while. :sweat_smile: 

Have a look at the following example if you need auto complete: https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/stories/examples/react-autosuggest.js

**Comment by EugeneSnihovsky** [comment]
@leMaik Hello. Thanks for great example with autocomplete. It seems that autocomplete work only for first tag. Then autocomplete list is not appeared. Can you help me please to solve this problem?
https://teamwertarbyte.github.io/material-ui-chip-input/?path=/story/chipinput--with-react-autosuggest

**Comment by leMaik** [comment]
@EugeneSnihovsky It's fixed in v2.0.0-beta.1: https://github.com/TeamWertarbyte/material-ui-chip-input/commit/1380b3e024f2954e796bd63bcd5429fd8cf5c3ba but that's for Material-UI v4. I'm sure you can back-port that commit for Material-UI v1/v3.
