### ISSUE TITLE
Floating label overlays chips when focus is lost

### ISSUE THREAD

**Issue by jzrandall** [TeamWertarbyte/material-ui-chip-input#259]
In the Floating Label Storybook story the floating label falls back down over the chips after the input loses focus.  I was experiencing it in my app and found that it's doing the same thing Storybook example
[Floating Label](https://teamwertarbyte.github.io/material-ui-chip-input/?selectedKind=ChipInput&selectedStory=with%20floating%20label&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

![image](https://user-images.githubusercontent.com/26276980/51606415-e03ac900-1edf-11e9-97a6-92b370b4a8d4.png)

**Comment by leMaik** [comment]
@jzrandall Thank you for reporting this bug, I just released a fix: https://github.com/TeamWertarbyte/material-ui-chip-input/releases/tag/v1.0.0-beta.13

**Comment by jzrandall** [comment]
@leMaik Thanks for the blazing fast turnaround on that!
