### ISSUE TITLE
Typescript typings are missing

### ISSUE THREAD

**Issue by kwskii** [TeamWertarbyte/material-ui-chip-input#260]
Doing a `npm i --save material-ui-chip-input`
Does not install typings, I thought this project had them?

![image](https://user-images.githubusercontent.com/10780503/51645605-f3728680-1f29-11e9-8b7a-fbd204ab795d.png)

**Comment by leMaik** [comment]
Only the `next` version for @material-ui/core >= 1.0.0 has them. You need to use `npm i material-ui-chip-input@next` if you're using the latest version of Material-UI (you should be using that).

Let me know if you need further help. :+1:
