### ISSUE TITLE
'clearInputValueOnChange' implementation bug and fix

### ISSUE THREAD

**Issue by papercuptech** [TeamWertarbyte/material-ui-chip-input#261]
Thanks for the component btw.

The online examples using `react-autosuggest` fail to show text input after the first tag has been entered. This appears to occur consequent to `clearInputValueOnChange` being true.

I also encounter this issue when using:
mui-chip-input 1.0.0-beta.13
react-autosuggest 9.4.3

Problem appears to be in `getDerivedStateFromProps()` which implements `clearInputValueOnChange`, in that it's not setting `newState.prevPropsValue` when it differs from `props.value` if `clearInputValueOnChange` is true. It seems `newState.prevPropsValue` should always be updated when `props.value` differs regardless, so change in value can continue to be detected. However, it also appears detecting the change is only required to implement `clearInputValueOnChange`; i.e. if it's false, likely no need to detect value changes to begin with.

Fix is simple. I can make a PR, but hoping someone will just incorporate code below as part of next beta update.
```js
static getDerivedStateFromProps (props, state) {
    let newState = null

    if (props.value && props.value.length !== state.prevPropsValue.length) {
      newState = { prevPropsValue: props.value }
      if (props.clearInputValueOnChange)
        newState.inputValue = ''
    }

    /* or if change detection only needed for clearInputValueOnChange */
    if (props.clearInputValueOnChange 
      && props.value && props.value.length !== state.prevPropsValue.length)
      newState = { prevPropsValue: props.value, inputValue: '' }
    

    if (props.disabled) {
      newState = { ...newState, focusedChip: null }
    }

    return newState
  }
```

**Comment by leMaik** [comment]
Thanks for the report and the fix. :clap: You would make my life just a tiny bit easier by providing a PR.
