### ISSUE TITLE
`setTimeout` in `onBlur` handler causes form to be submitted before `onChange` is fired

### ISSUE THREAD

**Issue by joelvh** [TeamWertarbyte/material-ui-chip-input#262]
I have a form that only has the chip input. When someone enters an email address and then clicks "submit" before the email address gets converted to a chip, the form submits as if the chip input is empty.

I  was trying to understand why  there is a delay and found that there is a `setTimeout` on blur, and want to know why  that is? For me to successfully submit my  form, I have to use `setTimeout` when the form submits to match the same 150ms delay that the input uses.

https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/src/ChipInput.js#L232

Can this be removed?

**Comment by joelvh** [comment]
I should note that I'm using `blurBehavior: 'add'`,  which is what causes this behavior.

**Comment by leMaik** [comment]
Thanks for the report! I'm pretty sure there is a reason for the `setTimeout` there. The timeout was introduced by #191, I have no idea what happens if we remove it. :disappointed:

**Comment by leMaik** [comment]
@joelvh Would you like to investigate this issue?

**Comment by joelvh** [comment]
@leMaik yeah, i'll be looking into this as best I can. Will comment back if I see anything related to #191

**Comment by joelvh** [comment]
@leMaik in my  haste, I didn't notice the comment there in the code explaining that the 'add' behavior waits for any other interaction with the input value (e.g. auto-complete). I don't think this should be a default behavior - there should be an option to delay the callback. I will see about making an update in that regard.

**Comment by leMaik** [comment]
@joelvh Oh, I didn't see the comment either. I'd really appreciate a PR that changes the default behavior.
