### ISSUE TITLE
Outlined ChipInput width bug

### ISSUE THREAD

**Issue by PoscherAlexander** [TeamWertarbyte/material-ui-chip-input#264]
The width of the ChipInput component with the attribute variant="outlined" is changing while inputting chips. It increases and the chips are not changing the line.

`<ChipInput  
    type="text" 
    name="txtTags" 
    margin="normal" 
    variant="outlined"
    onChange={ this.handleTxtTagsChange }
    label="Tags"
/>`

**Example:**
Before any input:
![issue_ui](https://user-images.githubusercontent.com/32486892/52110269-681b8400-2600-11e9-9201-2a6ba750bee2.PNG)

After inputting 1 chip:
![issure_ui_after1](https://user-images.githubusercontent.com/32486892/52110298-79649080-2600-11e9-8ba0-595b873c2d06.PNG)

Atfer inputting some more chips:
![issure_ui_after_some](https://user-images.githubusercontent.com/32486892/52110302-7e294480-2600-11e9-8aa1-a3d06489b5fe.PNG)

Version: 1.0.0-beta.13

**Comment by leMaik** [comment]
This might be related to #241. I'll have to look into that.

@PoscherAlexander  Would you like to look into how this can be fixed and submit a PR? :+1:

**Comment by PoscherAlexander** [comment]
@leMaik Thank you for your quick answer. I can try to fix it, but I am busy right now. So it will take some time.

**Comment by leMaik** [comment]
I'm pretty sure that I just fixed this. :tada: I'll publish a new version later today.
