### ISSUE TITLE
Is dataSource and dataSourceConfig still relevant ?

### ISSUE THREAD

**Issue by VincentCharpentier** [TeamWertarbyte/material-ui-chip-input#265]
I'm trying to migrate from legacy to 1.0 beta
I still see dataSource and dataSourceConfig listed in the options but it seems useless now.

After looking at the example it seems that I must use a third party for this (react-autosuggest).

Am I right ? If not, how to setup autocomplete without third party code ?

Thanks for your help

**Comment by leMaik** [comment]
You are right about the missing auto completion support (see our examples). `dataSource` and `dataSourceConfig` are still useful to display objects as chips, though.

**Comment by VincentCharpentier** [comment]
Thank for you quick reply, I will go with react-autosuggest.

Side note: It might be helpful to have a small text in these example to instruct user to start typing with 'a' or 'b'. At first I though it was broken when searching "France" and "United States"

**Comment by leMaik** [comment]
@VincentCharpentier You can submit a PR, if you want, to add more states or add that hint. :wink:

**Comment by leMaik** [comment]
I'll drop `dataSourceConfig`. I just implemented a component that uses react-autosuggest with a custom chip renderer and `dataSourceConfig` isn't helpful at all. I _want_ objects as chips, and I want to handle constructing a display value of that object myself.

Dropping `dataSourceConfig` will yield to more flexibility and simpler code. :sunglasses:

**Comment by richpixel** [comment]
@VincentCharpentier Can link to the example that shows how to use react-autosuggest with this component?

**Comment by VincentCharpentier** [comment]
Hi @richpixel ,
Sorry I'm not sure which example I was referring to but surely one on this repository.
Probably this one:
https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/stories/examples/react-autosuggest.js

**Comment by VincentCharpentier** [comment]
I'm going to close this as the question has been answered:
- dataSource is still relevant
- dataSourceConfig has been removed
