### ISSUE TITLE
override deleteIconStyle?

### ISSUE THREAD

**Issue by mailvidi** [TeamWertarbyte/material-ui-chip-input#267]
Is there an alternate to override the delete icon style in the chip?

As per material-ui, I can use "deleteIconStyle" to customize it.

I got this warning msg:
```
the key `deleteIconStyle` provided to the classes property is not implemented in ChipInput.
You can only override one of the following: root,inputRoot,input,chipContainer,outlined,standard,filled,labeled,label,labelShrink,helperText,inkbar,focused,disabled,underline,error,chip.
```

**Comment by leMaik** [comment]
You can use a custom `chipRenderer` to customize the chips. https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/stories/index.js#L73

**Comment by mailvidi** [comment]
Very cool, thanks so much!
