### ISSUE TITLE
The context `muiTheme` is marked as required in `ChipInput`, but its value is `undefined`.`

### ISSUE THREAD

**Issue by doorman02** [TeamWertarbyte/material-ui-chip-input#268]
I am getting the following errors:
```
`Warning: Failed context type: The context `muiTheme` is marked as required in `ChipInput`, but its value is `undefined`.`
```
and
```
ChipInput.js:722 Uncaught TypeError: Cannot read property 'prepareStyles' of undefined
    at ChipInput.render
```
Even after wrapping the ChipInput element using the  MuiThemeProvider theme={theme} element

Using Chrome, Visual Code, latest React, MaterialUI and ChipInput

**Comment by leMaik** [comment]
Which version of material-ui are you using? Which version of material-ui-chip-input?

**Comment by doorman02** [comment]
Hi @IeMaik I am using 
@material-ui/utils@3.0.0-alpha.3 and
 "material-ui-chip-input@0.19.0",
should I update to 1.0.0-beta.14 ?

**Comment by doorman02** [comment]
Hi @leMaik I updated to the beta.14 and the textfield is rendered correctly I get the foo bar chips already in the field. However when I chip I would expect the words to turn into a chip once I hit space. Do I need to handle this manually by adding new chips using the onUpdateInput event?

**Comment by leMaik** [comment]
@doorman02 Yes, material-ui-chip-input 0.x is for material-ui 0.x, and somehow we didn't publish a new major release (v1.0.0) yet. :roll_eyes: It confuses a lot of people, we really should to that.

> I would expect the words to turn into a chip once I hit space

The `newChipKeyCodes` prop is your friend, e.g. 

```
<ChipInput
    newChipKeyCodes={[13, 32]}
/>
```

…where 13 is enter and 32 is space.

**Comment by doorman02** [comment]
Thanks this worked well :)

**Comment by harryadel** [comment]
@doorman02 What's your `@material-ui/core` version? As, I've tried updating everything to the latest, but it didn't work!

**Comment by doorman02** [comment]
Hi @harryadel I am using "@material-ui/core": "^3.9.2",

**Comment by harryadel** [comment]
@doorman02 Thank you so much. It finally works! Also, here are my packages versions for anyone who might encounter this issue: 

```
"@material-ui/core": "^3.9.2",
"@material-ui/icons": "^3.0.2",
"@material-ui/utils": "^3.0.0-alpha.3",
"material-ui-chip-input": "^1.0.0-beta.14",
```

**Comment by manualva7** [comment]
This plugin doesn't work. None of the solutions provided help me get rid of the error.
