### ISSUE TITLE
classNamePrefix not defined in production when overriding Material UI's classname generator

### ISSUE THREAD

**Issue by davidcalhoun** [TeamWertarbyte/material-ui-chip-input#269]
First, thanks for this awesome library!  It's worked out super well, and I love that it's so customizable.

This is probably a bit of an edge case, but it looks like the `classNamePrefix` isn't defined, so I'm unable to customize the production CSS classname that gets outputted (via `react-jss`).

Note that this can't be reproduced in dev - it must be in prod mode (e.g. Webpack running in prod mode).

Example:

(be sure to also install `react-jss`, which is a transitive dependency of `@material-ui`)

```js
import React from 'react';
import MaterialUIChipInput from 'material-ui-chip-input';
import Chip from '@material-ui/core/Chip';
import JssProvider from 'react-jss/lib/JssProvider';

/**
 * Overrides CSS classname generation in production builds.
 */
let classNameIndex = 0;
const generateClassName = (rule, styleSheet) => {
  classNameIndex++;
  return `${ styleSheet.options.classNamePrefix }-${ rule.key }-${ classNameIndex }`;
}

function App() {
  return (
    <JssProvider generateClassName={ generateClassName }>
       <MaterialUIChipInput ... />
       <Chip ... />
    </JssProvider>
  );
}

export default App;
```

When outputted, `MaterialUIChipInput` will have CSS classes that look like this: `undefined-root-123`

Whereas Material UI components (like `Chip`) will have classes that look normal, like this: `MuiChip-root-123`

More info:
* https://material-ui.com/customization/css-in-js/
* https://github.com/marmelab/react-admin/issues/1782

**Comment by leMaik** [comment]
Good find and thank you for the code to reproduce this issue! :clap: 
Material-UI seems to use `MuiComponentName` as prefix. To prevent conflicts, we'll go with `WAMuiComponentName` for Team **W**ert**a**rbyte components.

None of our components currently support this, so if you want to submit some PRs, this is a great opportunity. :smile:

**Comment by davidcalhoun** [comment]
Great, thanks for the fast response!  :)  I'm just using this component at the moment, so this is all I need for now.

**Comment by leMaik** [comment]
@davidcalhoun Oh, I'm sorry. I'll publish a new version soon.
