### ISSUE TITLE
onDelete when using dataSourceConfig doesn't work

### ISSUE THREAD

**Issue by maximenathan** [TeamWertarbyte/material-ui-chip-input#272]
Thanks for this awesome library!
 
_using latest material-ui-chip-input_
I'm trying to manipulate custom object  instead of string for my Chips
I use `dataSourceConfig`  and it's working well except for `delete` on the icon (which return a string instead of my object)

Here is a [CodeSandbox](https://codesandbox.io/embed/z2pnmq82p4?fontsize=14)

_Delete a chip with the keyboard, then with the mouse_

Is it a normal behavior?

Thanks!

**Comment by leMaik** [comment]
Finally someone who is actually affected by #112.
This was the normal behavior but [it's been changed but not released yet](https://github.com/TeamWertarbyte/material-ui-chip-input/commit/242abcd4dd711b8ce069adac04b5a336f828a439) now, `onDelete` is now always called with the object. I'll add a test to ensure that clicking on the delete icon also calls `onDelete` with the chip object.

I'll publish a new release asap.

**Comment by maximenathan** [comment]
Thanks for the quick answer!
I just forked the project and didn't get what I did wrong because it seems to work well on `master`

**Comment by leMaik** [comment]
Indeed, it's supposed to work on `master`.

**Comment by leMaik** [comment]
I added a test to verify the new behavior (it fails when reverting the commit that fixes the behavior): https://github.com/TeamWertarbyte/material-ui-chip-input/commit/f30ec9ea3bb98f7b61a132cd56fa84cfa12f832a#diff-4f742f87662836961e34519006a2474cR208
