### ISSUE TITLE
The "classes" property in the type definition is required but not

### ISSUE THREAD

**Issue by m-kur** [TeamWertarbyte/material-ui-chip-input#273]
["Classes" property in type definition](https://github.com/TeamWertarbyte/material-ui-chip-input/blob/b3dc6a6635b82f40ca38616bbadc48a192791bba/typings/index.d.ts#L32) is required, but I think that it is optional like other properties. Is it correct?

**Comment by leMaik** [comment]
That's right. It should be updated to be optional everywhere. PR welcome, if you want. 😁
