### ISSUE TITLE
material-ui v4 support

### ISSUE THREAD

**Issue by sikorsky555** [TeamWertarbyte/material-ui-chip-input#275]
We are on version of @material-ui/core. I really like the functionality of this component. What are the plans for adding support for @material-ui/core v4?

**Comment by leMaik** [comment]
We'll update all our components. This is one of our most-used ones, so it has a slightly higher priority.

If you want to support us, feel free to give it a try and submit a PR. :+1:

**Comment by sikorsky555** [comment]
So we need to update all of the components to material-ui v4 at one time? How many components would that encompass? Would you expect this to be included in your v4 beta? I forked the repo and upgraded the component and it looks like it is pretty functional, we haven't noticed any issues yet. 

When I forked your repo, I ran into issues out of the gate with npm install and building storybook, so when I get some time, I will try to figured out this issue.

**Comment by leMaik** [comment]
> So we need to update all of the components to material-ui v4 at one time?

No, we can port them one by one.

>  I forked the repo and upgraded the component and it looks like it is pretty functional, we haven't noticed any issues yet.

Please submit a PR! :clap: 

> When I forked your repo, I ran into issues out of the gate with npm install and building storybook, so when I get some time, I will try to figured out this issue.

We'll figure that out when your PR is there. :wink:

**Comment by vinceliu21** [comment]
Is there an update on when a supported material-ui v4 version will be released?

**Comment by leMaik** [comment]
@vinceliu21 We maintain this project in our spare time. If you need it and want to speed up the process, feel free to support the project, e.g. by submitting a PR.

**Comment by leMaik** [comment]
Thanks to the great wotk of @leocabeza, I just published [v2.0.0-beta.1](https://github.com/TeamWertarbyte/material-ui-chip-input/releases/tag/v2.0.0-beta.1) that adds initial support for Material-UI v4. :tada: 

Please give it a try and file new issues if there's anything missing or if you encounter any bugs.
