### ISSUE TITLE
Not work on Android Chrome

### ISSUE THREAD

**Issue by megastas** [TeamWertarbyte/material-ui-chip-input#277]
Can't add a chip in Android Chrome, newChipKeyCodes={[13, 188]}, keys not working. Thanks.

**Comment by leMaik** [comment]
https://github.com/TeamWertarbyte/material-ui-chip-input/issues/198

**Comment by leMaik** [comment]
I'll look into this issue. It's a bit weird, I have one app where `keyUp` works perfectly with keyCode 13 on Android.

**Comment by megastas** [comment]
@leMaik Thanks. Issue is with a Next key, with Go all ok. Adding of TAB keyCode  (9) doesn't helps, this is how I fixed this:
`     onBlur={e => {
          if(e.target.value) {
            input.value.push(e.target.value)
            input.onChange(input.value);
          }
          input.onBlur();
        }`
If somebody don't understand, I use https://redux-form.com, this is my full code for chip field:
`  renderChipsField = ({ input, label, helperText, custom }) => {
    return (
      <ChipInput
        {...input}
        clearInputValueOnChange={true}
        helperText={this.isMobile() ? helperText : null}
        onUpdateInput={e=> {
          let value = e.target.value;
          if(value.indexOf(",") !== -1 && value !== ",") {
            let outArray = value.split(",");
            if(!outArray[outArray.length-1]) {
              outArray.splice(-1,1)
            }
            this.props.change(input.name, outArray);
          }
        }}
        fullWidth
        margin="normal"
        newChipKeyCodes={[13, 188]}
        value = { input.value || []}
        onAdd={(addedChip) => {
          let values = input.value || [];
          values = values.slice();
          values.push(addedChip);
          input.onChange(values);
        }}
        onDelete={(deletedChip) => {
          let values = input.value || [];
          values = values.filter(v => v !== deletedChip);
          input.onChange(values);
        }}
        onBlur={(e) => {
          if(e.target.value) {
            input.value.push(e.target.value)
            input.onChange(input.value);
          }
          input.onBlur();
        }
        }
        label={!this.isMobile() ? label : custom && custom.mobileLabel}
      />
    )};`

**Comment by leMaik** [comment]
@megastas You should be able to get the same behavior when using `blurBehavior='add'` :thinking:
