### ISSUE TITLE
blurBehavior change default to 'add' not 'clear'

### ISSUE THREAD

**Issue by bonbonio** [TeamWertarbyte/material-ui-chip-input#279]
I feel this would make more sense than clearing it when the focus changes... when entering a single value, people do not instinctively press return/space/comma, they just click the next field.

This is also based on a round of UI testing done internally, and the "add" value made a huge difference.

Just a suggestion.

**Comment by leMaik** [comment]
Good point. :thinking: This would be a breaking change, though, but I see why this would be good.

**Comment by leMaik** [comment]
Since this is a breaking change, it's not going to happen in v1 (i.e. the Material-UI v1+v3 version). But in v2.0.0-beta.2, this is changed, so it will default to add in the Material-UI v4 version.
