### ISSUE TITLE
Missing errorText prop

### ISSUE THREAD

**Issue by joshjg** [TeamWertarbyte/material-ui-chip-input#28]
The `errorText` prop of material-ui's [SelectField](http://www.material-ui.com/#/components/select-field) and [TextField](http://www.material-ui.com/#/components/text-field) components doesn't seem to be implemented here.

**Comment by leMaik** [comment]
Whoops... I'll fix that asap. :+1:

**Comment by leMaik** [comment]
Supported as of v0.6.0.

**Comment by joshjg** [comment]
Thanks for the quick fix!
