### ISSUE TITLE
Consider clsx instead of classnames

### ISSUE THREAD

**Issue by CrocoDillon** [TeamWertarbyte/material-ui-chip-input#283]
Material UI uses [`clsx`](https://www.npmjs.com/package/clsx) instead of `classnames` since v4, see mui-org/material-ui/pull/14152 for reasons and discussion.

Might make sense to start using `clsx` for `material-ui-chip-input` as well to make sure it isn't the reason people end up with two class name utilities in their bundles. Should be a drop-in replacement, I can make a PR if desired.

Related: #275 #280

**Comment by leMaik** [comment]
Thanks for the reminder, I'd like to use clsx for our v4-compatible version. :+1: Would you maybe like to continue the work on #280? Unfortunately, there's not much progress lately.

**Comment by CrocoDillon** [comment]
Great! I might have time in the weekend or early next week to look at it if there is still little progress by then 😄

**Comment by leMaik** [comment]
@CrocoDillon The work on the Material-UI v4 support continues on the `next` branch. :sunglasses: I replaced classnames with clsx there. Thanks to #280, it already looks pretty nice, I'll release a beta version later. 

If you find any bugs in the new version, your help would be highly appreciated. We don't use v4 in any project yet, unfortunately.

**Comment by CrocoDillon** [comment]
Okay great, looking forward to the release.

I do have issues with vertical alignment (seems to be caused by #278). Vertical alignment of the chips with the input element is off. Especially when rendering a small chip. Not sure if this is Material UI v4 specific though.

**Comment by leMaik** [comment]
@CrocoDillon Please open a new issue and provide a screenshot or, even better, a Code Sandbox that reproduces the issue.

**Comment by CrocoDillon** [comment]
Done, see #285.
