### ISSUE TITLE
Documentation issue related to @material-ui/core version

### ISSUE THREAD

**Issue by morissonmaciel** [TeamWertarbyte/material-ui-chip-input#284]
Hi guys,
I'm having this error when trying to import `material-ui-chip-input` in my React project, and probably is a misunderstood related to `installation notes` documentation:

```
./node_modules/material-ui-chip-input/lib/ChipInput.js
Module not found: Can't resolve '@material-ui/core/FilledInput/FilledInput'
```

My project has the following dependencies:
```json
"@material-ui/core": "3.0.3",
"@material-ui/icons": "3.0.1",
```

In the `Installation Notes` from main `GitHub` page, versions from `@material-ui` prior `1.0.0` are listed as compatible. But, for those who are using `@material-ui/core` under the `3.1.0` version, dependency issues may happen even if the documentation doesn't clarify these cases.

When installing latest version from `@material-ui/core` (`4.3.0`) the following warning was thrown by `npm`, but no error occurs while importing the package:

```
npm WARN material-ui-chip-input@1.0.0-beta.17 requires a peer of @material-ui/core@^1.0.0 || ^3.1.0 but none is installed. You must install peer dependencies yourself.
```

Can you guys please comment about this problem?
Thanks in advance.

**Comment by leMaik** [comment]
You're using a pretty old version of @material-ui 3.0. Maybe update to the latest 3.0 version. Looks like we don't _actually_ support v3.1.0 because of `FilledInput` :thinking:

**Comment by leMaik** [comment]
If you want to use material-ui/core 4.x, you'll have to use material-ui-chip-input@2.0.0-beta.1 (2.x is for Material-UI 4.x)
