### ISSUE TITLE
migration guide

### ISSUE THREAD

**Issue by oprogramador** [TeamWertarbyte/material-ui-chip-input#286]
It would be great if you provided a migration guide showing what I should do exactly to migrate from `material-ui-chip-input@0` to `material-ui-chip-input@1`.

**Comment by leMaik** [comment]
material-ui-chip-input@0 is for Material-UI 0.x
material-ui-chip-input@1 is for Material-UI 1.x – 3.x
material-ui-chip-input@2 is for Material-UI 4.x

The API is pretty much the same (the breaking changes are documented in the change log, see [the releases page](https://github.com/TeamWertarbyte/material-ui-chip-input/releases)).

**Comment by oprogramador** [comment]
Thanks @leMaik 

I changed the field names:
- `hintText` -> `helperText`
- `onNewRequest` -> `onAdd` (I'm not sure here but I haven't found anything more relevant)
- `floatingLabelText` -> `label`
- `onBeforeRequestAdd` -> `onBeforeAdd`
- `onRequestAdd` -> `onAdd`
- `onRequestDelete` -> `onDelete`

However it looks in this way:
<img width="238" alt="Screenshot 2019-08-07 at 21 21 10" src="https://user-images.githubusercontent.com/8701039/62651484-65a43900-b959-11e9-977c-273330017235.png">

**Comment by leMaik** [comment]
That looks like an issue with your other components / complete layout. Maybe provide a Code Sandbox so I could have a short look on it?

**Comment by oprogramador** [comment]
This must be about `material-ui-chip-input` before downgrading it fixes the problem.

**Comment by leMaik** [comment]
You might be using the wrong version for your version of Material-UI, as I said in my first comment.

**Comment by oprogramador** [comment]
It fails for both the newest `material-ui@4` and the newest `material-ui@3`.

**Comment by leMaik** [comment]
Again,

> You might be using the wrong version for your version of Material-UI, as I said in my first comment.

**Comment by leMaik** [comment]
@oprogramador I'll close this after 10 days without response. Feel free to re-open this if you need further help while updating your project.

**Comment by oprogramador** [comment]
Thanks for help.

I don't need this any longer.
