### ISSUE TITLE
Support for readOnly prop

### ISSUE THREAD

**Issue by billsaysthis** [TeamWertarbyte/material-ui-chip-input#287]
We need support for readOnly (separate from disabled) especially in CSS, is this something that can be added?

**Comment by leMaik** [comment]
@billsaysthis  Good idea! What exactly do you mean by "especially in CSS"? Material-UI's `readOnly` `TextField` looks like the normal one but is, well, non-writeable.

Would you like to submit a PR? Most likely you'll have to set the `readOnly` attribute of the `Input` component used in the chip input. :thinking:
