### ISSUE TITLE
Customizing single chip

### ISSUE THREAD

**Issue by vithu30** [TeamWertarbyte/material-ui-chip-input#288]
Is it possible to change chip color based on any condition.
For instance, if the added chip satisfies certain condition, it should be able to distinguish in UI by using different colors.
I tried _chipRenderer_ and it seems like it changes the color of all added chips.
Appreciate any help on this.

**Comment by leMaik** [comment]
You can indeed use the `chipRenderer` prop to achieve this. Could you please show your code, e.g. as a code sandbox?

**Comment by vithu30** [comment]
@leMaik Thanks for the response. I found the issues in my code and now it is working as expected.
