### ISSUE TITLE
Is there a way to remove delete icon from chip?

### ISSUE THREAD

**Issue by makssie** [TeamWertarbyte/material-ui-chip-input#289]
I know I can change classes, but there are some default classes, and i want to remove the "X" icon from chip.

Is there a way to remove it like below?

```

const styles = {
  icon: { 
    display: 'none'
  }
}

<ChipInput
classes={{
icon: classes.icon
}}
/>
```
Thanks

**Comment by leMaik** [comment]
There is, you can use a custom chip renderer: https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/stories/index.js#L74
