### ISSUE TITLE
Empty chips-array when value is set to empty array.

### ISSUE THREAD

**Issue by nypraise** [TeamWertarbyte/material-ui-chip-input#290]
How can I empty the chips array when value is set to empty array?

`const [collectionChips, handleChipChange] = useState();`

`                            <ChipInput
                                variant='outlined' 
                                value={collectionChips}
                                clearInputValueOnChange
                                label='Add Tags'
                                placeholder='Press enter key to add tag'
                                helperText='Press enter key to add tag'
                                style={{ width: '80%', marginBottom: '30px' }}
                                onChange={(chips) => handleChipChange(chips)}
                            />`

**Comment by leMaik** [comment]
Your initial state shouldn't be `undefined`, but an empty array. So it should be `useState([])`, otherwise the component starts in _uncontrolled_ mode and then gets controlled and doesn't work properly.
