### ISSUE TITLE
Autosuggest only works for adding the first chip

### ISSUE THREAD

**Issue by TylerRick** [TeamWertarbyte/material-ui-chip-input#293]
In the [with react-autosuggest](https://teamwertarbyte.github.io/material-ui-chip-input/?selectedKind=ChipInput&selectedStory=with%20react-autosuggest&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) example, the autocomplete works for adding the first tag, but after adding the first tag, if you start typing in the text field again to search for another country, nothing happens. Actually, if you type "a", the list of options appears, but what I expect to happen instead is:

- it works identically to how it let me search for the first chip
- it displays the characters that I type (currently nothing shows up if I start typing after a chip is selected)

It would be nice if it worked like react-select. (See, for example, https://material-ui.com/components/autocomplete/ and https://codesandbox.io/s/eq08w.)

**Comment by leMaik** [comment]
Turns out that this bug was fixed long ago and I just didn't update the Storybook on GitHub pages. :man_facepalming: 

The updated demo is available here: https://teamwertarbyte.github.io/material-ui-chip-input/?path=/story/chipinput--with-react-autosuggest
