### ISSUE TITLE
The readOnly property does not exist

### ISSUE THREAD

**Issue by gchumillas** [TeamWertarbyte/material-ui-chip-input#296]
The `readOnly` property does not exist in the list of available properties, but it was documented in README. When I use this component in combination with TypeScript I get the following compilation error:

```
Property 'readOnly' does not exist on type 'IntrinsicAttributes & Props & { children?: ReactNode; }'
```
You can fix it by writing instead:
```XML
<ChipInput InputProps={{ readOnly: true }} ... />
```

**Comment by leMaik** [comment]
But it's right there: https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/typings/index.d.ts#L60

If you know how to fix this, feel free to submit a PR. 👍

**Comment by leMaik** [comment]
Just found out that this was due to v1.1.0 and v2.0.0-beta.2 not being released yet, which introduce the new prop. They are released now. :tada:
