### ISSUE TITLE
with autocomplete, custom filter, open on focus #question

### ISSUE THREAD

**Issue by voxbox-io** [TeamWertarbyte/material-ui-chip-input#30]
Hi
Could you provide the source of the example 'with autocomplete, custom filter, open on focus' ?
Grazie

**Comment by leMaik** [comment]
It's already open source. :wink: Please have a look at https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/stories/index.js#L59

**Comment by voxbox-io** [comment]
I must have been sleeping this morning!
👍

**Comment by voxbox-io** [comment]
I have one question though: can I use a custom dataSourceConfig = {
      text: 'text',
      value: 'value',
    }
or does it only support flat array?

Thanks

**Comment by leMaik** [comment]
It will support this soon, see #9.
