### ISSUE TITLE
dataSource is not working

### ISSUE THREAD

**Issue by shinyr** [TeamWertarbyte/material-ui-chip-input#306]
dataSource is not working for material ui chip input.
I need to use material UI and a chip input field that will be autocomplete to search existing chips and should be able to create new chips also.
please help me to solve this.
Thanks in advance.

**Comment by stuckinaboot** [comment]
Any update on this?

**Comment by durchanek** [comment]
You may also consider this solution using Material UI directly: https://material-ui.com/components/autocomplete/#multiple-values

**Comment by leMaik** [comment]
The [examples in the storybook](https://github.com/TeamWertarbyte/material-ui-chip-input/tree/master/stories) work just fine for me. If you need further help, please provide some actual code or code sandbox so that we can help you.

**Comment by yuriy-voypost** [comment]
Hi! 

What I am expecting with `dataSource` prop - when I add flat array of strings to `dataSource` property, on input autocomplete I want to see strings from `dataSource` as suggestions for adding chips. If my expectations are right it's not working correctly. 

Storybook has `dataSource` example but it's comment out (`/*...*/`). 
For example this one ("controlled input with auto complete"):
` 
.add('controlled input with auto complete', () =>
    <ControlledChipInput
      openOnFocus
      dataSource={['foo', 'bar']}
      inputProps={{ fullWidth: true }}
    />
  )
`
Maybe this feature deprecated? 

I uncommented this code from storybook and `dataSorce` not working as I expected. 

How can I solve this?
