### ISSUE TITLE
Size prop not working

### ISSUE THREAD

**Issue by gradinarot** [TeamWertarbyte/material-ui-chip-input#314]
Even when we pass size="small" to the component the size stays the same.

Screenshot: [https://prnt.sc/rup9kq](url)

`
<ChipInput
                  fullWidth
                  size="small"
                  variant="outlined"
                  defaultValue={['foo', 'bar']}
                  onChange={(chips) => {}}
                />
`

**Comment by leMaik** [comment]
There is no size prop, use `margin` instead, like here: https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/stories/index.js#L294

**Comment by gradinarot** [comment]
Thank you for that fast response, but I already tried that. I need to make the size smaller so it looks like the other components on the page, not apply margin.

Found a temporal fix by changing the InputRoot outlined class padding to 0px. 
Thanks anyway.

**Comment by gradinarot** [comment]
@leMaik do you know whats the reason why ctrl+v is not pasting text into the field?

**Comment by tonyking97** [comment]
Hi @gradinarot, Can you share the code snippet of how to make the chipInput size small? Thank you.

**Comment by Void1315** [comment]
> Hi @gradinarot, Can you share the code snippet of how to make the chipInput size small? Thank you.
try this
`chipInput: {
      marginBottom: '0px !important',
    },
    ChipInputinputinputRoot: {
      paddingTop: '0px !important',
    },
    ChipInputinput: {
      paddingBottom: '4px !important',
    },`
    `<ChipInput
                 
                  fullWidth
                  classes={{
                    chip: classes.chipInput,
                    inputRoot: classes.ChipInputinputinputRoot,
                    input: classes.ChipInputinput,
                  }}
                  // label={label}
                  // helperText={chipsError}

                  size="small"
                  variant="outlined"
                />`
