### ISSUE TITLE
Previous chips are not saved when entering new chip

### ISSUE THREAD

**Issue by shigawaka** [TeamWertarbyte/material-ui-chip-input#316]
When I try to add a new chip after inputting data the chip state doesn't include the previously entered chip. 
![chips](https://user-images.githubusercontent.com/12228888/81795336-96477d80-953e-11ea-8c45-4df72c89baf8.PNG)

As shown in the image above. chip state is empty so whenever I enter new chip. Previous chips would be deleted.

**Comment by leMaik** [comment]
Looks like you're not using controlled mode correctly. Please take a look at the examples over here: https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/stories/index.js
