### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by paillave** [TeamWertarbyte/material-ui-chip-input#319]

**Comment by paillave** [comment]
Issue opened by mistake :)

**Comment by leMaik** [comment]
@paillave So I guess you found [our TypeScript definitions](https://github.com/TeamWertarbyte/material-ui-chip-input/tree/master/typings)? :smile:

**Comment by paillave** [comment]
Well, yes I did. But I actually didn't want to open a case. It was done by mistake. Sorry! :-)
