### ISSUE TITLE
Material-ui/core older versions are not supported, it crashes

### ISSUE THREAD

**Issue by hanzlahabib** [TeamWertarbyte/material-ui-chip-input#323]
Hi,  i have read that you only support latest version of material-ui/core but in installation docs it is listed that material-ui@1.0.0 version is compatible with material-ui-chip-input,

i noticed there are many developers who are using old material-ui/core and they don't want to update it due to big project or any specific reason, now how they can use latest-material-ui-chip-input with older version of material-ui/core

is this good idea for individual to fork project and make changes which make it possible to use on older material-ui/core version and publish it as new package and then use that in their projects

can't we have 2 packages in community, containing all bug fixes but compatible with older versions of material-ui/core ?

only difference i encountered in latest versions you introduces variants, which are not present in older versions, what if someone don't need that and want to use latest input chip package with older material-ui/core

i hope you find better way to support both older and latest versions of material-ui/core

thanks,

**Comment by leMaik** [comment]
This project only supports Material-UI 1.x and 3.x (and 0.x via the legacy branch, see the readme). Material-UI v4 has its own chip input so there's no need to provide another one.

Updating from MUI v1 to v3 is pretty straight forward.

**Comment by hanzlahabib** [comment]
@leMaik  thanks for the response, 
our current material-ui/core version is 1.3.0 something
we cannot afford updating it currently,
when we try to use latest version of material ui chips input it fails beause in material-ui/core there is no
```
'@material-ui/core/FilledInput/FilledInput'
'@material-ui/core/OutlinedInput'
```

for example in our situation we really don't need these variants for chips, so i just forked and removed these dependent packages, that did job for us,
now we are using older version of material-ui and latest verison of material-ui-chips-input

can we make these variants optional which will work for older versions too

**Comment by leMaik** [comment]
@hanzlahabib Allright, got it. Unfortunately, dropping the two variants would mean that we'll have to drop the `variants` prop and find a different way to support different input components (maybe with an `InputComponent` prop, but how do we handle additional styles, e.g. `classes[variant]` then?). This would be a breaking change for all users that use this with Material-UI v3.

Maybe you can submit a PR with your modified version which I could then publish under a special tag to npm, e.g. `material-ui-chip-input@mui-v1`?

**Comment by hanzlahabib** [comment]
@leMaik  yes, but anyone who is using this modified pr version they should be aware that variants are no longer supported, in this modified version

here is pacakge which i recently published, i forked this project and create new branch and modify it and build it and publish it on npm and that i am using in my current project 

https://www.npmjs.com/package/material-ui-chip-input-without-variants

there is no big change just removed props from enum and remove import of those variants, 
and build the project 
if you still want pr let me know,

**Comment by leMaik** [comment]
> yes, but anyone who is using this modified pr version they should be aware that variants are no longer supported, in this modified version

Obviously, but the variants were never supported with Material-UI v1. Since you already published the package, I'd prefer not to publish another package and just drop v1 support then. Doesn't seem to affect a lot of people (you are the first one to report the broken compatibility since we added variants in **October 2018**.
