### ISSUE TITLE
Using semicolon for setting new chips

### ISSUE THREAD

**Issue by appukuttan-shailesh** [TeamWertarbyte/material-ui-chip-input#325]
I was previously making use of **newChipKeyCodes** to set new chips. I used to have:
`newChipKeys={[13, 186]}`

But then I realized this works on Chrome but fails on Firefox as firefox has the keycode 59 for SemiColon, unlike Chrome which uses 186.
Usefool tool to check: https://keycode.info/

So then based on the discussion here (https://github.com/TeamWertarbyte/material-ui-chip-input/issues/271), I moved to using **newChipKeys**. I used:
`newChipKeys={['Enter', 'Tab', ';']`
and also
`newChipKeys={['Enter', 'Tab', 'Semicolon']`

But neither of these are producing new chips with semi-colon.
I can still form new chip with tab and enter.

What is the problem? How can I get it to work with semicolon?

**Comment by appukuttan-shailesh** [comment]
Oops.... my bad! Just realized it was a mistake at my end in passping props between components. I had forgotten to change the parameter name to "newChipKeys" when setting the property.

**Comment by leMaik** [comment]
@appukuttan-shailesh Glad you figured it out :+1: Please feel free to reach out if you discover another issue or need any help with the chip input.
