### ISSUE TITLE
dataSource doesn't appear to have any effect

### ISSUE THREAD

**Issue by davidjan3** [TeamWertarbyte/material-ui-chip-input#328]
I'm looking for a way to limit the user input to preset tags. Thus it would be nice to have an autocompletion, so the user knows what tags they can add. From the docs it read dlike dataSource should do the trick - but it doesn't appear to have any effect...?

**Comment by leMaik** [comment]
There is no auto completion in the version for MUI v1 and later. You could use Material UI's chip input instead: https://material-ui.com/components/autocomplete/

**Comment by davidjan3** [comment]
For some reason I didn't find that one when I was looking for a Material-UI version of Angular Material's Chip Input. It's exactly what I'm looking for, so thanks alot for showing me the obvious that I didn't see :D
