### ISSUE TITLE
Chip Limit prop

### ISSUE THREAD

**Issue by brandonhdz** [TeamWertarbyte/material-ui-chip-input#330]
I was looking for a way to set a limit on the amount a chips. ie:

```
<ChipInput 
    defaultValue={chipItems}
    style={{width: '50%'}}
    chipLimit={5}
/>  
```

I tried doing this manually with the available poperties but none seem to pass an array of current chips to the callback function.

**Comment by brandonhdz** [comment]
Update: I found the following [Issue #299 ](https://github.com/TeamWertarbyte/material-ui-chip-input/issues/299) which was closed, however, it would be super useful to do something like `limitTags` prop in the Autocomplete component:
```
      <Autocomplete
        multiple
        limitTags={2}
        id="tags-standard"
        options={top100Films}
        getOptionLabel={(option) => option.title}
        defaultValue={[top100Films[13], top100Films[12], top100Films[11]]}
        renderInput={(params) => (
          <TextField {...params} variant="outlined" label="limitTags" placeholder="Favorites" />
        )}
      />
```
However, that only hides the extra chips as opposed to having an actual max input.

[source](https://deploy-preview-20209--material-ui.netlify.app/components/autocomplete/#limit-tags)

**Comment by leMaik** [comment]
@brandonhdz Just as I said in #299: You can already achieve this in controlled mode. What would be the benefit of adding another prop for this and complicating the internal logic further?
