### ISSUE TITLE
prevent the addition of chips with no value inside 

### ISSUE THREAD

**Issue by elizad** [TeamWertarbyte/material-ui-chip-input#332]
which is the best way to prevent the addition of chips with no value inside?

```
<ChipWrapperDiv invalid={invalid}>
      <ReactChipInput
        classes="ChipAppVersionRule"
        chips={chips || [] }
        onSubmit={handleAddChip}
        onRemove={handleRemoveChip}

      />
    </ChipWrapperDiv>
```

**Comment by leMaik** [comment]
@elizad Wrong project so I transferred it but then realized that your issue is for react-chip-input. Please refer to [the react-chip-input repo](https://github.com/shhdharmen/react-chip-input#readme).
