### ISSUE TITLE
Update material-ui/core dependency

### ISSUE THREAD

**Issue by gregroyal** [TeamWertarbyte/material-ui-chip-input#334]
"@material-ui/core": "^1.0.0 || ^3.1.0" is out of date is there a reason for the locked version?

as of today, https://www.npmjs.com/package/@material-ui/core is at 4.11.0

**Comment by gregroyal** [comment]
I was able to use the new Autocomplete with freeSolo to recreate this project. Maybe thats why the version is locked?

**Comment by hamidehnouri** [comment]
Hello!
I have a problem with underline that I have mentioned in this issue :
https://github.com/TeamWertarbyte/material-ui-chip-input/issues/343
would you please show me how did you recreate chip input with autocomplete without options ?
