### ISSUE TITLE
Problem with material-ui dep

### ISSUE THREAD

**Issue by 41y08h** [TeamWertarbyte/material-ui-chip-input#338]
```
Failed to compile.

./node_modules/material-ui-chip-input/lib/ChipInput.js
Module not found: Can't resolve '@material-ui/core/Chip' in '<...project_path>\node_modules\material-ui-chip-input\lib'

```

Unsure about deps in this module? 
PS.- I'm not using material-ui yet in my project!

**Comment by 41y08h** [comment]
### Works only when material-ui installed! Would be great to include it in main dep in `package.json`

**Comment by leMaik** [comment]
@41y08h material-ui/core is a peer dependency. This project is named material-ui-chip-input and its description clearly states "chip input field for Material-UI".
