### ISSUE TITLE
style bug on safari

### ISSUE THREAD

**Issue by trelly** [TeamWertarbyte/material-ui-chip-input#34]
"-webkit-appearance: textfield" show border on safari. 
![image](https://cloud.githubusercontent.com/assets/172466/20035956/d1223b48-a433-11e6-969c-7ad8664c0dfd.png)

**Comment by leMaik** [comment]
@trelly Please try `style={{ outline: 'none !important' }}`. I'll add it as default is that fixes the problem (I don't have access to Safari for testing right now).

**Comment by taxigy** [comment]
```
<ChipInput
  inputStyle={{appearance: 'none'}}
  ...props />
```
worked for me.

**Comment by leMaik** [comment]
Does the border appear _by default_? I'd put @taxigy's fix in the code, if so.

**Comment by leMaik** [comment]
@trelly @taxigy I can't reproduce this bug on an iPad with (probably) latest Safari. Does the ugly border appear by default or because you have some CSS rule that _adds_ the border?
I can't fix this without any feedback. :confused:
