### ISSUE TITLE
Chip input under line is not shown after updating to material-ui version 5.0.0-alpha.23

### ISSUE THREAD

**Issue by hamidehnouri** [TeamWertarbyte/material-ui-chip-input#343]
Hello!
Chip input under line is not shown after updating to material-ui version 5.0.0-alpha.23. 
Underline is shown on focus and hover but not on the normal mode. I have also tried "disableUnderline={false}" but it doesn't work.
The issue seems to be about the color of the border-bottom of the div which contains the input. 
During the last hours I have been struggling to solve this underline issue but I have not found a workaround solution for it. 
I really appreciate if you fix this issue or show me a temporary workaround.
Here is a sample code on codeSandbox:
https://codesandbox.io/s/quizzical-lederberg-31hn1?file=/src/ValueFilterMultiple.js

**Comment by leMaik** [comment]
Material-UI 5.0 is not and will not be supported.
The autocomplete component of Material-UI provides the same and even more features since v4: https://material-ui.com/components/autocomplete/#multiple-values
