### ISSUE TITLE
Set keyCode for rendering new Chip in prop

### ISSUE THREAD

**Issue by admacleod** [TeamWertarbyte/material-ui-chip-input#35]
It would be helpful to be able to set the keycode for triggering the creation of a new prop to be on a key other than 13 (enter).

I have created an example of how this could be done in my own fork but it seems like something that could be useful for everyone.

**Comment by arunondeck** [comment]
I'm also looking for the same.

**Comment by leMaik** [comment]
@admacleod Pull requests welcome! :+1:

**Comment by leMaik** [comment]
@admacleod I improved your solution so that it supports more than one key code, e.g. `[188, 13, 32]` (space, enter, comma) seems to be a good combination.
