### ISSUE TITLE
"future" compatibility issue

### ISSUE THREAD

**Issue by osher** [TeamWertarbyte/material-ui-chip-input#354]
![image](https://user-images.githubusercontent.com/803101/126947411-ffa1bcaf-df37-427c-ba64-cf356c2ffa07.png)

Exposed by npm 7.

Current work-around is to use legacy modules-resolution model, which might be silences other problems.

**Comment by leMaik** [comment]
Since Material-UI v4, it has a built-in autocomplete component that can do everything this module can and much more. That's why we won't update material-ui-chip-input.
