### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by muzzamilshaikh** [TeamWertarbyte/material-ui-chip-input#355]
### I'm getting this in AWS codebuild

ModuleNotFoundError: Module not found: Error: Can't resolve '@material-ui/core/FormHelperText' in '/codebuild/output/src968353347/src/node_modules/material-ui-chip-input/lib'

how should I resolve this error

**Comment by leMaik** [comment]
You're probably using an unsupported version of Material-UI. v5 is not supported.
