### ISSUE TITLE
chip input and chip showing up on different lines

### ISSUE THREAD

**Issue by arunondeck** [TeamWertarbyte/material-ui-chip-input#36]
![1 chip_on_same_line](https://cloud.githubusercontent.com/assets/2003354/20142438/ad68f126-a6cf-11e6-8f9e-8327a83a70fd.png)
This is the chip input as shown on the [demo page](https://teamwertarbyte.github.io/material-ui-chip-input/?selectedKind=ChipInput&selectedStory=with%20auto%20complete&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel)

But what I have shows up on different lines always. 
![2 chip_on_diff_line](https://cloud.githubusercontent.com/assets/2003354/20142240/e6bfdc88-a6ce-11e6-97e2-f3ed930d3d00.png)

And this is without any properties set on the chipInput. Not sure if this is an issue or I messed up, is this by design? If yes, how do I make it like the demo page?
Thanks!

**Comment by leMaik** [comment]
The input field jumps onto the next line if there isn't enough space left on the last line, so this is by design. On the demo page, I use `fullWidth` so that the component takes up the available width.

**Comment by arunondeck** [comment]
Thank you! So by setting a min-width I am able to get it to the same line.
