### ISSUE TITLE
Two chips added when clicking autocomplete menu item

### ISSUE THREAD

**Issue by kyteague** [TeamWertarbyte/material-ui-chip-input#40]
Looks like it's a regression in the 0.9.0 release, specifically this commit: https://github.com/TeamWertarbyte/material-ui-chip-input/commit/a6e266dc18a2649205b563b96a60c1f3919e6ab8#diff-acb87ac4d1cdb3b6518879923e905559L164

Another call to handleAddChip() was added to the handleItemTouchTap().  Simply commenting out that line fixes the issue.

**Comment by leMaik** [comment]
I can't reproduce this, but I'll remove the line that was added.

**Comment by leMaik** [comment]
I'm afraid I can't reproduce this bug. Could you please provide code that reproduces the bug?

**Comment by sever2715** [comment]
@leMaik, I found this bug too :confused:

```jsx
class DoubleChipApp extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            tags: []
        };
    }

    handleRequestAdd(chip) {
        console.log('added chip', chip)
        const addToEnd = function (array, item) {
            array.push(item);
            return array;
        };
        this.setState((prevState, props) => ({
            tags: addToEnd(prevState.tags, chip)
        }));
        return true;
    }

    handleRequestDelete(chip) {
        this.setState((prevState, props) => ({
            tags: prevState.tags.filter((tag) => tag !== chip)
        }));
        return true;
    }

    render() {
        return (
            <MuiThemeProvider>
                <ChipInput value={this.state.tags}
                           openOnFocus
                           dataSource={['one', 'two']}
                           onRequestAdd={this.handleRequestAdd.bind(this)}
                           onRequestDelete={this.handleRequestDelete.bind(this)}
                />
            </MuiThemeProvider>
        )
    };
}

ReactDOM.render(
    <DoubleChipApp />,
    document.getElementById('app'),
);
```

**Comment by leMaik** [comment]
I'll fix this later, thanks for the example! :+1:

**Comment by leMaik** [comment]
Fixed it, will release soon. :tada: 

@sever2715 You are _mutating_ the state in `handleRequestAdd` by using `push`, which modifies the array. You should better create a _new_ array that has the new chip added, e.g. with `[...array, item]`. That way, you would work around the bug because calling `handleRequestAdd` wouldn't have any side-effects. :wink:

**Comment by sever2715** [comment]
@leMaik thank you for your advice, but I already used another hack(my app is async - therefore it is [necessary](https://facebook.github.io/react/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous) to consider the previous state).
 :relaxed: :space_invader:
