### ISSUE TITLE
Uncaught Invariant Violation: addComponentAsRefTo

### ISSUE THREAD

**Issue by sever2715** [TeamWertarbyte/material-ui-chip-input#41]
- fail-case.jsx:

```jsx
import React from 'react'
import ReactDOM from 'react-dom'
import MuiThemeProvider from "material-ui/styles/MuiThemeProvider";
import ChipInput from 'material-ui-chip-input'
import injectTapEventPlugin from "react-tap-event-plugin";
injectTapEventPlugin();


const App = () => (
    <MuiThemeProvider>
        <ChipInput
            defaultValue={['foo', 'bar']}
        />
    </MuiThemeProvider>
);

ReactDOM.render(
    <App />,
    document.getElementById('app'),
);
```

- fail-case.html:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>: (</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab&amp;subset=cyrillic" rel="stylesheet">
</head>
<body>
    <div id="app"></div>
    <script src="fail-case.jsx.js"></script>
    </body>
</html>
```

- browser console output:

```
bundle-final.jsx.js:32161 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

**Comment by leMaik** [comment]
@sever2715 Did you make sure that you have only one copy of React loaded? I've never seen this error while using this component, and your example is pretty trivial.

**Comment by sever2715** [comment]
Hello @leMaik!

You are right, indeed it was in the two versions of the loaded React libraries(already exist `15.4.0-rc.4` and `15.3.2` dependence for material-ui-chip-input).
To solve my problem downgrade it to `15.3.2`.

Thank you for a wonderful component!

**Comment by leMaik** [comment]
@sever2715 Glad that you could solve this. material-ui-chip-input only dev-depends on react, so it shouldn't be a problem to use a newer version of React, though. But well, it's npm, resolving dependencies is unpredictable anyway. :sweat_smile:

Thank you for using muci. :)
