### ISSUE TITLE
Peer dependencies warnings on updates

### ISSUE THREAD

**Issue by Sharlaan** [TeamWertarbyte/material-ui-chip-input#42]
Hello !

just a heads up, not really an "issue" but when im updating my dependencies i'm always getting these warnings with your packages:

> npm WARN material-ui-chip-input@0.11.0 requires a peer of react@~15.3.2 but none was installed.
npm WARN material-ui-chip-input@0.11.0 requires a peer of react-tap-event-plugin@^1.0.0 but none was installed.
npm WARN material-ui-password-field@1.0.2 requires a peer of material-ui@~0.15.4 but none was installed.
npm WARN material-ui-password-field@1.0.2 requires a peer of react@~15.3.1 but none was installed.
npm WARN material-ui-password-field@1.0.2 requires a peer of react-tap-event-plugin@^1.0.0 but none was installed.

Any solution ?

P.S.: the versions of mentioned missing deps are actually way ahead, like react@15.4 or react-tap-event-plugin@2.0.1

**Comment by leMaik** [comment]
Until yesterday evening, react 15.4, react-tap-event-plugin@2 and material-ui were a complete disaster. :bomb: :smile: Meanwhile the issues seem to be fixed, I'll update the peer dependencies soon.

**Comment by Sharlaan** [comment]
What is the usefulness of the peerDependencies prop in package.json ?
Why not simply put them in dependencies ? this would solve those questionable loud warnings at each minor updates of x dep...

**Comment by leMaik** [comment]
@Sharlaan Because that would cause even more issues by installing certain versions of the dependencies automatically.
That's what peer dependencies are there for, and the warnings are actually your friends (material-ui-chip-input doesn't work with react@15.4 and r-t-e-p@2 at the moment). :wink:
