### ISSUE TITLE
Displaying value when using an object array for dataSource and dataSourceConfig

### ISSUE THREAD

**Issue by arunondeck** [TeamWertarbyte/material-ui-chip-input#44]
Hi, 
I have an array of objects `[{value:'IN',text:'India'},{value:'CA',text:'Canada'}...]` as datasource and my dataSourceConfig is `{text:'text', value: 'value'}`.

The autocomplete dropdown has the value of text inside them (India,Canada etc) but after selection the chips displayed have the value of value key. (IN,CA etc). I am unable to display the text and wasnt able to figure out any option to do the same. 
Inside value I tried setting it as selections.value but that doesn't display anything. Is that a bug?

**Comment by leMaik** [comment]
I'm afraid I can't reproduce this. The following code works as expected:

```jsx
<ChipInput
  dataSource={[{value:'IN',text:'India'},{value:'CA',text:'Canada'}]}
  dataSourceConfig={{ text: 'text', value: 'value' }}
/>
```

Maybe you are using the component as _controlled_ component and don't add `{ value: '...', text: '...' }` objects to the array of chips but only strings with the key names?

**Comment by leMaik** [comment]
@arunondeck Is this still an issue or did you fix this in your application?

**Comment by arunondeck** [comment]
@leMaik Hi, sorry about not replying sooner. It is not an issue. I was using chipRenderer and had messed up some variable inside that.
