### ISSUE TITLE
Handle `onPaste` with line breaks in text

### ISSUE THREAD

**Issue by umidbekkarimov** [TeamWertarbyte/material-ui-chip-input#45]
I had a problem with users pasting data from spreadsheets to chip input and it creates one big chip with all values: 

![screen shot 2016-11-27 at 18 31 47](https://cloud.githubusercontent.com/assets/4734297/20649060/d7933aca-b4cf-11e6-9706-427a8c250e5f.png)

First workaround was to `chip.split(' ')`, but it create another problem - when customers wanted to search by values with `' '` inside ("Firstname Lastname")

Second workaround:

```javascript
const onChipRequestAdd = (...chips) =>  filter.mergeChips(chips)

<ChipInput
  onPaste={(event) => {
    event.preventDefault() // prevent default behavior
    onChipRequestAdd(...event.clipboardData.getData('Text').split('\n'))
  }
  hintText="Search"
  value={chips}
  onRequestAdd={onChipRequestAdd}
  onRequestDelete={onChipRequestDelete}
 />
```

And it works perfectly as I expected.

I think current behavior should be by default or at least optional

**Comment by leMaik** [comment]
Nice workaround! I'm not sure if this should be added to the component as it is, though.

There is a prop `newChipKeyCodes` that specifies key codes that "break" chips while typing (only `13` by default). If you could automatically determine the corresponding characters and split by those characters, I'd love to see a PR from you! :+1:

**Comment by umidbekkarimov** [comment]
@leMaik oh, thanks for fast response  👍

`newChipDelimiter` - will be good ? 
or something like `clipboardTextDelimiter` - that would only work with paste?
also current behavior needs some updates cause it will submit value every time when user paste value.

____
So:

* `addOnPaste: bool` - will prevent default `onPaste` behavior and request to add value from clipboard
* `clipboardTextDelimiters: arrayOf(string)` - will split text from clipboard by passed delimiters
* or `parseClipboardText: func` - function to create array from clipboard text
* `addOnPasteMultiple: bool` - will prevent default `onPaste` only if clipboard text was split to array with more than one chip

**Comment by leMaik** [comment]
@umidbekkarimov After re-thinking this... That's really a _lot_ of additional complexity for the single use-case of copying stuff from a spreadsheet. :confused: I'd like to add one, or even no new props at all.

As you see, the intended behavior can already be achieved by using `onPaste`, so there is no need for new props.

**Comment by umidbekkarimov** [comment]
@leMaik agree. I can add it as an example to the storybook in case if someone will need similar functionality.

**Comment by leMaik** [comment]
@umidbekkarimov That would be great! I'll update the story book so that you can see the source code for the examples there.

**Comment by umidbekkarimov** [comment]
@leMaik thank you 👍 I wish today I will have free time to contribute 😅
