### ISSUE TITLE
Object doesn't support property or method 'assign' (IE 11)

### ISSUE THREAD

**Issue by jduhls** [TeamWertarbyte/material-ui-chip-input#47]
I will try to solve with https://babeljs.io/docs/plugins/transform-object-assign/

![screen shot 2016-11-28 at 11 21 15 am](https://cloud.githubusercontent.com/assets/3170699/20678590/e7972dea-b55c-11e6-85bb-8ee759411879.png)

**Comment by leMaik** [comment]
Whoops, we totally forgot about ugly browsers. :wink: Material-UI also uses `Object.assign`, so I won't try to remove it. I'm glad that you found a solution, might be useful for other people having the same problem.

**Comment by jduhls** [comment]
Material-UI uses https://www.npmjs.com/package/simple-assign . That said, I abandoned trying to support IE 11. However, I was able to solve the initial problem with https://babeljs.io/docs/plugins/transform-object-assign/
