### ISSUE TITLE
Backspace to remove chip doesn't work with dataSource

### ISSUE THREAD

**Issue by madvas** [TeamWertarbyte/material-ui-chip-input#49]
For some reason, when I use ChipInput with dataSource and dataSourceConfig I can no longer use backspace to remove chips. Everything else works fine about a ChipInput. When I remove dataSource and dataSourceConfig, I can use backspace to remove chips.

**Comment by leMaik** [comment]
I'm afraid I'm unable to reproduce this using the latest version.

Please have a look at the examples in the [storybook](https://teamwertarbyte.github.io/material-ui-chip-input/), e.g. `with auto complete` and `controlled input with auto complete`. The source code of the stories might also help you find the issue.
