### ISSUE TITLE
Filled and blurred floatingLabelText doesn't match opaque TextField labelColor

### ISSUE THREAD

**Issue by zigzackattack** [TeamWertarbyte/material-ui-chip-input#50]
When muiTheme's labelColor is changed to an opaque color (with an opacity of anything other than 0.498039), a filled and blurred ChipInput's floating label no longer matches the label of a TextField in the same state. On [Line 39](https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/src/ChipInput.js#L79), the floatingTextLabel color is faded when the label is filled and unfocused.

Here's an example with `muiTheme.palette.labelColor: rgba(158, 158, 158, 1)`

<img width="463" alt="screen shot 2016-12-02 at 4 19 23 pm" src="https://cloud.githubusercontent.com/assets/2507776/20854744/40a23726-b8ab-11e6-972e-347531318519.png">

Is there a way to support label colors that aren't 50% transparent?

**Comment by leMaik** [comment]
Thank you for the bug report. Looks like Material UI [changed the way the floating label color is calculated](https://github.com/callemall/material-ui/commit/354ceafeb2d4d2c1fca70895d16ec8a94c3e15f6) in v0.16.2. I'll update this component accordingly. :+1:

**Comment by zigzackattack** [comment]
Awesome! Great component by the way!

**Comment by leMaik** [comment]
Sorry, I was pretty busy this week. Could you please check if the latest version fixes this?

**Comment by zigzackattack** [comment]
Yep fix looks great! Thanks!
