### ISSUE TITLE
A way to customise style Chip item

### ISSUE THREAD

**Issue by Vishal0203** [TeamWertarbyte/material-ui-chip-input#51]
Hi, how do I add a class to the chip item? 
I see the documentation talks only about the styles to the root element.

**Comment by leMaik** [comment]
Hi @Vishal0203, you can style the chips by using a custom `chipRenderer`. Please take a look at [this story](https://github.com/TeamWertarbyte/material-ui-chip-input/blob/1833fb113d74adf7a25c4358bf82615ec7751f83/stories/index.js#L97) to see how it works.

**Comment by Vishal0203** [comment]
Okay that works, but I think there is a problem with handleRequestDelete. Upon clicking the cross handle request delete only passes the value of the chip and not the complete chip.

**Comment by leMaik** [comment]
Uhm... that's the intended behaviour. :open_mouth:

**Comment by Vishal0203** [comment]
let me elaborate. 

```
       <ChipInput
              value={this.state.tags}
              onRequestAdd={(tag) => this.handleTagAdd(tag)}
              onRequestDelete={(deletedTag) => this.handleTagDelete(deletedTag)}
              dataSource={{name: 'Something', tag_guid: '123-567'}}
              dataSourceConfig={[{text: 'name', value: 'tag_guid'}]}
              hintText="Add tags to your question for easy visibility."
              openOnFocus={true}
              fullWidth
              chipRenderer={({ text, value, isFocused, isDisabled, handleClick, handleRequestDelete }, key) => (
                <Chip
                  key={key}
                  className="chip"
                  labelStyle={this.styles.chipLabel}
                  onTouchTap={handleClick}
                  onRequestDelete={handleRequestDelete}
                >
                  {text}
                </Chip>
              )}
            />
```

and my `handleRequestDelete` is as follows

```
this.setState({
        tags: this.state.tags.filter((c) => c !== deletedTag)
      })
```

For backspace, `deleteTag` receives `{name: 'Something', tag_guid: '123-567'}` but on clicking 
`x`,  `deleteTag` receives `123-567` (and hence doesn't remove the tag unless I explicitly handle this condition)

**Comment by leMaik** [comment]
This is indeed a bug, thank you for the report! :-) I'll fix it asap and publish a new release.
