### ISSUE TITLE
Inconsistent argumentt for onRequestDelete callback

### ISSUE THREAD

**Issue by leMaik** [TeamWertarbyte/material-ui-chip-input#52]
Originally reported by @Vishal0203 in #51.

```
       <ChipInput
              value={this.state.tags}
              onRequestAdd={(tag) => this.handleTagAdd(tag)}
              onRequestDelete={(deletedTag) => this.handleTagDelete(deletedTag)}
              dataSource={{name: 'Something', tag_guid: '123-567'}}
              dataSourceConfig={[{text: 'name', value: 'tag_guid'}]}
              hintText="Add tags to your question for easy visibility."
              openOnFocus={true}
              fullWidth
              chipRenderer={({ text, value, isFocused, isDisabled, handleClick, handleRequestDelete }, key) => (
                <Chip
                  key={key}
                  className="chip"
                  labelStyle={this.styles.chipLabel}
                  onTouchTap={handleClick}
                  onRequestDelete={handleRequestDelete}
                >
                  {text}
                </Chip>
              )}
            />
```

and my `handleRequestDelete` is as follows

```
this.setState({
        tags: this.state.tags.filter((c) => c !== deletedTag)
      })
```

For backspace, `deleteTag` receives `{name: 'Something', tag_guid: '123-567'}` but on clicking 
`x`,  `deleteTag` receives `123-567` (and hence doesn't remove the tag unless I explicitly handle this condition)

**Comment by advance512** [comment]
This was not fixed, right?

onRequestAdd receives an object (if you use `dataSource` and `dataSourceConfig`) while onRequestDelete receives a string, being just the value of the item in the data source.

e.g.

```
onRequestAdd({ label: "Some label", value: "SOME_ENUM_VALUE"});
onRequestDelete("SOME_ENUM_VALUE");

```

**Comment by leMaik** [comment]
It _was_ fixed, but in the other way: `onRequestDelete` no _always_ gets called with the value (which is either the string or the `value` property when using `dataSourceConfig`.

**Comment by advance512** [comment]
Isn't this inconsistent?

You get the item in one, the value in another. Sure, sometimes the item is a string, sometimes it contains a text/label and the value string.

Seems to me that it would be more consistent to stick to either value or the complete item. 

Anyways, I work around it by translating it so I can use it in redux-form.

**Comment by leMaik** [comment]
Yes, but at least it's consistent for `onRequestDelete` calls, which it wasn't before. Making it consistent between `onRequestAdd` and `onRequestDelete` would be a breaking change, unfortunately (and I don't want to break everyone's code even if this is < 1.0.0).
I could do that when I update this to material-ui@next and bump the version to 1.0.0, though. :+1: Could you please open a new issue for that?

**Comment by advance512** [comment]
Done. Awesome work, btw. :)

I'll probably wrap it in a new lib, that support redux-form and that can integrate into Google Places. Soonish or laterish

**Comment by leMaik** [comment]
Thank you, @advance512 :relaxed: 
That sounds like a good idea. I have an example for formsy support [here](https://github.com/TeamWertarbyte/material-ui-chip-input/issues/2#issuecomment-247402164), it may help you when building a redux-form wrapper.
Let me know when you're done, I'd like to link that as related project. :wink:

**Comment by advance512** [comment]
I have the redux-form wrapper, actually. I had to split it into two:
A "multi-select" and a "tags input". The reason is that with a DataSource, I need to use onRequestAdd, but without one, I need to use onChange (which, btw, gives you the complete list of items, also a tad inconsistent, but there IS only one handler).

I don't have time to port my existing, _ugly_, component that merge `react-places-autocomplete` and `react-select` to do the Google Places thing, but I will soon - it's the only non-Material UI component I currently use.
