### ISSUE TITLE
Displaying selected value

### ISSUE THREAD

**Issue by TeeShastry** [TeamWertarbyte/material-ui-chip-input#53]
Hi Chipinput team,

I am trying to display the selected values that comes from database by doing it this way.
```jsx
<ChipInput
	fullWidth
	openOnFocus
	dataSource={props.dropdownlistdata}
	clearOnBlur={true}
	value={['test1','test2']}
	hintText="Try typing a..."
/>
```

1. It works fine in the sense that it displays the selected text specified in the value and also it does not have that option available anymore in the dropdownlist values which is perfect. But when I choose anything else from the dropdown nothing else is getting selected. Always the value of 'test1 and test2 is the thing that is getting selected.

2. The other thing is mine is a stateless component and the dropdownlist values comes from database from a master table and selected values comes from a transaction table. I don't think it is an issue, it is more of how can we achieve the preselected values from a different set of array and still have the dropdownlist values. your advise is much appreciated!

Can you please suggest? 

_leMaik: Slightly formatted the text and added numbers to the questions._

**Comment by TeeShastry** [comment]
I don't think it is an issue, it is more of how can we achieve the preselected values from a different set of array and still have the dropdownlist values. your advise is much appreciated!

**Comment by leMaik** [comment]
Hi @TeeShastry,

1. You specified the `value` prop so you're in _controlled_ mode but don't handle adding chips with the `onRequestAdd` prop. You need to add a `onRequestAdd` function or use the _uncontrolled_ mode by specifying the initially selected chips with `defaultValue`. The stories in this repo provide some examples.

2. Just specify some chips as `defaultValue` or put them in the array that you use as `value` to achieve preselected values. The `dataSource` is independant from the value, so you can just put the values from the database into it and that's it.

I hope I could help!

**Comment by leMaik** [comment]
Whoops, didn't mean to close this.

**Comment by leMaik** [comment]
@TeeShastry I'm closing this issue since it's been over a month without a response. Feel free to ping me if you have further questions. :+1:
