### ISSUE TITLE
add transform-object-assign babel plugin

### ISSUE THREAD

**Issue by rhythnic** [TeamWertarbyte/material-ui-chip-input#54]
Thanks for this component.  It looks good and is stable.  Would you consider adding the [transform-object-assign babel plugin](https://www.npmjs.com/package/babel-plugin-transform-object-assign)?  I have a requirement to support IE11.  I'll probably update my webpack config to run material-ui-chip-input through babel, but just wanted to mention it to you in case you want to support IE11.

**Comment by leMaik** [comment]
Absolutely! :+1: This would also fix issues like #47.
@rhythnic Would you like to send a PR?

**Comment by leMaik** [comment]
Fixed by #55
