### ISSUE TITLE
Always open auto-complete menu on click

### ISSUE THREAD

**Issue by marcacyr** [TeamWertarbyte/material-ui-chip-input#57]
![qelqfiwcyu](https://cloud.githubusercontent.com/assets/4146617/21153921/6234a4c2-c121-11e6-9b56-95fe5ba572aa.gif)

Description of gif:

Click on the input, menu opens first time. Make a selection. Focus returned to input, chip added successfully, but the menu does not reopen. 

The issue I'm running into is that when clicking in the autocomplete box, the menu opens correctly the first time. After clicking, or keying down to and selecting, an option the chip is added correctly, and focus is returned to the autocomplete input, but the menu does not reopen *until* the user hits a keyboard key (any key does the trick, but they must hit a key). Clicking again doesn't re-open the menu. No action other than a keydown/keyup on the keyboard does the trick.

I've been digging through the module code and I see the places where focus is returned to the AutoComplete component. Theoretically, this should do the trick but it isn't. I can't for the life of me figure out why the menu is not reopening. Have tried a number of things and have put debuggers all over the material-ui-chip-input lib code to try to find the cause, but have come up empty so far.

Any ideas?

**Comment by leMaik** [comment]
In your gif, you aren't actually de-focusing the input field (the cursor stays in it). That's why the menu doesn't re-open. I agree that the menu should open on click, though. I'll add that in the next version. :+1:

**Comment by amit1911** [comment]
+1

**Comment by marcacyr** [comment]
Ah, okay so @leMaik if I force a de-focus and re-focus on the input then it should work as expected. I can handle that on my end. Thanks for the guidance! Will comment back once I get it working.

**Comment by amit1911** [comment]
@marcacyr @leMaik i think it's a useful feature to have so it is better if we can implement this in the library itself rather than each of us handling it individually.

**Comment by leMaik** [comment]
I agree with @amit1911; this should be fixed. :+1:

**Comment by marcacyr** [comment]
Thank you @leMaik for doing this! When is this going to be released (if there is an ETA?)

**Comment by leMaik** [comment]
@marcacyr Either today or next week. I'd like to fix #65 before publishing the next release.

**Comment by leMaik** [comment]
@marcacyr Publishing v0.11.4 right now! :tada:
