### ISSUE TITLE
Chip not added when Autocomplete open on load

### ISSUE THREAD

**Issue by amit1911** [TeamWertarbyte/material-ui-chip-input#58]
Hi, The onRequestAdd callback is not fired when I select an item from the autocomplete menu for the first time but it works fine after that. Take a look at the following gif
![bug](https://cloud.githubusercontent.com/assets/3509404/21209862/e6197ed4-c2b1-11e6-8b02-a9e490374fa4.gif)

My chipInput component is as follows
```
<MuiThemeProvider>
    <ChipInput
        value={value}
        dataSource={dataSource}
        onRequestAdd={onRequestAdd}
        onRequestDelete={onRequestDelete}
        openOnFocus={true}
        onUpdateInput={onUpdateInput}
        open
    />
</MuiThemeProvider>
```
I noticed that this issue happens only when the  `open` prop is passed to `ChipInput` component. The `open` prop is not handled by ChipInput and is directly passed to AutoComplete component which will open it on load without requiring user focus. After investigating I found out that the ChipInput's `this.autoComplete.handleItemTouchTap` function is not being called and instead the Autocomplete's `handleItemTouchTap` function is called on first click. But on second click onwards, the ChipInput's `handleItemTouchTap` is called so it works fine.

Other info :- 
react: 15.4
material-ui: 0.16.5
material-ui-chip-input: 0.11.2

**Comment by leMaik** [comment]
Wow, never tested the `open` prop. 😅 Thank you for reporting!

Looks like the new `handleItemTouchTap` function is assigned too late... I'll look into this later.
