### ISSUE TITLE
Width doesn't set through style property

### ISSUE THREAD

**Issue by ashl1** [TeamWertarbyte/material-ui-chip-input#6]
Seems, width set to ```undefined``` in https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/src/ChipInput.js#L312 if ```fullWidth``` isn't set.
I recommend to initialize structure with ```if``` statement instead of explicit using ```undefined``` with ternary operator. This prevent rewriting attributes defined in ```style``` property.
Another approach is to use ```style``` attributes as backup values, but this do impossible to use another extend. The best safe operation is not to initialize the object attribute with any (include ```undefined```) value, as I write above.

**Comment by leMaik** [comment]
:open_mouth: Whoops... I didn't know that `Object.assign({foo: 42},{foo: undefined})` results in `{foo: undefined}`. I'll change this to an `if` structure, as you suggested, which will be more readable, too.
