### ISSUE TITLE
Webpack throws error after babel-plugin-transform-object-assign was added

### ISSUE THREAD

**Issue by ajdalshov** [TeamWertarbyte/material-ui-chip-input#62]
ERROR in ./~/material-ui-chip-input/lib/ChipInput.js
Module build failed: ReferenceError: Unknown plugin "transform-object-assign"

**Comment by leMaik** [comment]
I can't reproduce this bug. Could you please explain to me when this occurs or perhaps even add a minimal example? Thanks in advance!

**Comment by leMaik** [comment]
Closing this after a month without any response. :disappointed:
