### ISSUE TITLE
Options to trigger onRequestAdd when losing focus

### ISSUE THREAD

**Issue by quangbuule** [TeamWertarbyte/material-ui-chip-input#63]
Currently the `clearOnBlur` is fine, but in some cases, adding current input text to value list when losing focus is better UX. What do you say?

**Comment by leMaik** [comment]
Indeed, there might be use cases where adding the  current input text would be better. E.g. when the user just wants to "tab through the form" and doesn't realize that the field is not a normal text field.

How do you think should this be implemented? We could add a new `addOnBlur` prop, but I think replacing the `clearOnBlur` prop with `blurBehavior = {'clear', 'add', null}` would be a simpler and more future-proof approach?

**Comment by quangbuule** [comment]
My best practice is always pass event to the handler (usually first arguments). I means in the ChipInput component, the `onRequestAdd` should be call like this:
```js
this.props.onRequestAdd(e, value);
```

Then the usage could be like this:
```js
<ChipInput
  [...]
  onRequestAdd={
    (e, value) =>
      e.type === 'blur' ?
        doSomethingOnInputBlur() :
        doSomethingOnNormalSelect()
  }
/>
```

Reference:
https://developer.mozilla.org/en-US/docs/Web/API/Event/type

**Comment by quangbuule** [comment]
For backward compatible, we could implement follow this interface:
```onRequestAdd(value: any, type: string)```

**Comment by leMaik** [comment]
Hm... And then you'd just keep `clearOnBlur`?

**Comment by leMaik** [comment]
@quangbuule That won't work in uncontrolled mode, though. There is no `onRequestAdd` in uncontrolled mode, so there would be no way to control if a chip should be added on blur.

**Comment by quangbuule** [comment]
True, what do you think about always add value when blur, there would be no `clearOnBlur`. Could you please explain why we do `clearOnBlur`?

**Comment by leMaik** [comment]
Usually, you _want_ to clear on blur to make clear that the value was not added. Sometimes (e.g. your use-case) you want to add the input value on blur. That are two different, but valid use cases and I don't want to remove one of them to support the other.

**Comment by quangbuule** [comment]
`blurBehavior` is fine for that.

Personally, I prefer always add on blur is better (then clear on blur is optional), People usually afraid to press Enter (the form may submit), and may not understand that Enter (or comma...) is a delimiter, they just enter a value (or select some values and the last value they left the last input) then focus on another field.

People may delete the last value without pain when they lose focus on the input while it is having content.

**Comment by quangbuule** [comment]
Just have a check on other tags input plugins (legacy), they work as I said:

https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/
http://xoxco.com/projects/code/tagsinput/example.html

**Comment by leMaik** [comment]
> Personally, I prefer always [...]

You prefer that. I also prefer that. But there are people (and users) who don't. :wink: 

> People may delete the last value without pain when they lose focus on the input while it is having content.

Sure, but good UX is about not frustrating the user and saying that they can just undo something that went wrong. We should let the users of this library decide what they (or their customers) want, so I think that `blurBehavior` is the way to go.

**Comment by quangbuule** [comment]
Great, go for it!

**Comment by leMaik** [comment]
Thanks to @jamieparkinson, we now have [a story that shows how to add chips on blur](https://teamwertarbyte.github.io/material-ui-chip-input/?selectedKind=ChipInput&selectedStory=add%20text%20input%20value%20on%20blur&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel).
