### ISSUE TITLE
Invalid positioning of Popover element with `openOnFocus=true`

### ISSUE THREAD

**Issue by umidbekkarimov** [TeamWertarbyte/material-ui-chip-input#68]
![jan-08-2017 19-04-47](https://cloud.githubusercontent.com/assets/4734297/21750811/64fb4666-d5d5-11e6-9c1d-e167f14ec2c1.gif)

Material UI AutoComplete removes `anchorEl` on [close](https://github.com/callemall/material-ui/blob/master/src/AutoComplete/AutoComplete.js#L241)
So when ChipInput calls [focus](https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/src/ChipInput.js#L192) `anchorEl` is null, and popover positions itself wrong
___

I could not reproduce this issue in the storybook, guess it's problem with async behavior of `this.setState`

**Comment by umidbekkarimov** [comment]
Found it, after upgrading deps to

```
 material-ui  ^0.16.2  →  ^0.16.6 
 react        ^15.4.0  →  ^15.4.2 
 react-dom    ^15.4.0  →  ^15.4.2 
```

![jan-08-2017 19-14-53](https://cloud.githubusercontent.com/assets/4734297/21750866/cf76a340-d5d6-11e6-8cd5-47afa12240bc.gif)

**Comment by leMaik** [comment]
Thank you for investigating this and providing the fix! I'll publish an update right now.
