### ISSUE TITLE
Cannot read property 'state' of null

### ISSUE THREAD

**Issue by MarkMurphy** [TeamWertarbyte/material-ui-chip-input#71]
Hello again :) 

Came across this error after installing this today:

```
ChipInput.js:176 Uncaught TypeError: Cannot read property 'state' of null
```

This seems to be the offending line (in the `handleInputBlur` handler):

```
if (!_this.autoComplete.state.open || _this.autoComplete.requestsList.length === 0) {
```

Steps to reproduce:

```
<ChipInput
  hintText="To"
  fullWidth={true}
  dataSource={['David Keefe', 'Sara Wellbrook', 'Johnathan Ives', 'Alanna Murphy']}
  onChange={(chips) => {}}
/>
```

Click on the input to give it focus. Press the down arrow key.

**Comment by leMaik** [comment]
This is strange... `this.autoComplete` is set when the component is mounted, and it seems to work fine in the [storybook](https://teamwertarbyte.github.io/material-ui-chip-input/?selectedKind=ChipInput&selectedStory=with%20auto%20complete&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel). I'll try to reproduce this again later. :+1:

**Comment by MarkMurphy** [comment]
Maybe `this` is bound to something other than the component instance.

**Comment by leMaik** [comment]
But `this` is always bound to the component inside the `render` function, unless you are calling it from the outside in a strange way.

**Comment by MarkMurphy** [comment]
Yeah, weird. I'm using react@15.4.2 in case that makes a difference.

**Comment by MarkMurphy** [comment]
I've made a local copy on ChipInput, investigating further...

**Comment by MarkMurphy** [comment]
I'm not yet sure how but when it happens `this` is referring to the AutoComplete not the ChipInput.

**Comment by leMaik** [comment]
@MarkMurphy Whaaat? :open_mouth: It's an arrow function, so `this` should be the `ChipInput`.

**Comment by MarkMurphy** [comment]
Yeah I know 😕

**Comment by MarkMurphy** [comment]
ok so I managed to get it working but can't explain why it was an issue at the moment. I changed the the AutoCompete ref property to a string and then added an accessor to the ChipInput:

```javascript
class ChipInput extends Component {
  // ...

  get autoComplete() {
    return this.refs.autocomplete
  }

  render() {
    // ...
    <AutoComplete ref="autocomplete" ... />
  }
}

The error stopped occurring after that. I feel like I've seen something somewhere in the react docs that mention about using functions in a ref

**Comment by leMaik** [comment]
Using strings as `ref` is deprecated. :confused:

**Comment by MarkMurphy** [comment]
Oh really? I didn't know that, can you point me to some docs?

**Comment by leMaik** [comment]
@MarkMurphy Yep, see my edit.

**Comment by MarkMurphy** [comment]
Thanks, back to the drawing board I guess.

**Comment by MarkMurphy** [comment]
I'm stumped. It's calling the `handleInputBlur` method with the autocomplete node as the backing context. I don't understand how that's possible...

**Comment by leMaik** [comment]
@MarkMurphy I have no idea what's going on right now, either.

**Comment by MarkMurphy** [comment]
ok, dev console is being weird. It was what was reporting `this` as being the autocomplete node while paused in the debugger. However when I hover over the the `this` keyword in the inspector is shows it as being the ChipInput but the autoComplete property IS null. 

![screenshot 2017-01-19 16 08 34](https://cloud.githubusercontent.com/assets/873474/22123324/9d3902ae-de61-11e6-9715-4c043eea4336.png)
![screenshot 2017-01-19 16 08 46](https://cloud.githubusercontent.com/assets/873474/22123325/9d3b52a2-de61-11e6-93f1-bc05fd2f3e14.png)

**Comment by leMaik** [comment]
A cheap "fix" would be to just check for `null` in the event handler. I don't get why it is called before the component is mounted.

**Comment by MarkMurphy** [comment]
I believe I've found the problem. I think it has something to do with this:

> If the ref callback is defined as an inline function, it will get called twice during updates, first with null and then again with the DOM element. This is because a new instance of the function is created with each render, so React needs to clear the old ref and set up the new one. You can avoid this by defining the ref callback as a bound method on the class, but note that it shouldn't matter in most cases.

[Caveats - Refs and the DOM - React](https://facebook.github.io/react/docs/refs-and-the-dom.html#caveats)

![screenshot 2017-01-19 16 19 43](https://cloud.githubusercontent.com/assets/873474/22123727/1f20ceea-de63-11e6-8a4f-98311b4f3250.png)

The problem goes away when I use a bound method on the class as suggested:

```js
class ChipInput extends Component {
  setAutoComplete = (ref) => {
    this.autoComplete = ref;
  }

  render() {
    // ...
    <AutoComplete ref={this.setAutoComplete} ... />
  }
}
```

**Comment by MarkMurphy** [comment]
I'll do up a pull request

**Comment by leMaik** [comment]
Great!
