### ISSUE TITLE
openOnFocus breaks blur

### ISSUE THREAD

**Issue by cauld** [TeamWertarbyte/material-ui-chip-input#73]
When setting openOnFocus to true the original collapsed state of the input is not reset when focus is lost. The label remains floated and the input is still underlined.

[This setState block](https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/src/ChipInput.js#L225) is never hit to set isFocused back to false.

You can see this in [the open on focus storybook example](https://teamwertarbyte.github.io/material-ui-chip-input/?selectedKind=ChipInput&selectedStory=with%20auto%20complete%2C%20open%20on%20focus&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel). Click into the input and then tab out. Doing the same in other examples where openOnFocus  is not used demonstrates the proper behavior.

**Comment by leMaik** [comment]
Thank you for the bug report and locating the issue. :+1: Would you like to submit a PR that fixes it?

**Comment by cauld** [comment]
I played around with this for a while. It is a minor timing issue. There might be a better way to handle this, but so far this is the simplest solution I've come up.

**Comment by leMaik** [comment]
Well, it's kind of an ugly hack, but that's the trade-off when you try to re-use components that aren't really made for making new components. :confused: Hopefully, this will improve when the next branch of Material-UI is ready and the chip input can be ported to use it.

Thank you for the fix! :+1:

**Comment by cauld** [comment]
Agreed, no problem. Will you be doing a new release soon that includes this fix? Would like to switch back to the official npm package.

**Comment by leMaik** [comment]
@cauld Thanks for the hint, I just released v0.12.2 which includes the fix. :+1:
