### ISSUE TITLE
inputStyle prop not modifying input color. 

### ISSUE THREAD

**Issue by MrPolymath** [TeamWertarbyte/material-ui-chip-input#75]
I'm basically adding the following prop `inputStyle={{'color':'rgba(255,255,255,1)'}}` but the input color is still black. How can I modify it?

**Comment by leMaik** [comment]
Maybe you want to modify the `textFieldStyle` prop instead of the `inputStyle` prop? It should be propagated to the input element, though, so it's strange that it doesn't have any effect.

**Comment by MrPolymath** [comment]
I've just tried both, `inputStyle ` and `textFieldStyle` and none of them propagates the color. 

The amazing part is that when I do: `textFieldStyle={{color:'rgb(255,255,255)', fontSize:'30px'}}`, the font size is changed to 30px but the color stays black.

**Comment by leMaik** [comment]
Seems to be a Material-UI issue that I can't fix then. :disappointed: Maybe the label color isn't meant to be changed (except if you use themes, you can change the label color with [themes](http://www.material-ui.com/#/customization/themes)).
