### ISSUE TITLE
Highlight broken with object values

### ISSUE THREAD

**Issue by Shaxmatist** [TeamWertarbyte/material-ui-chip-input#77]
When chips is array of strings blue highlights works normaly. When chips is array of objects first "Backspace" doesn't highlight chips. This can be seen at the storybook.

**Comment by leMaik** [comment]
Thank you for the bug report, I'll fix this asap.

**Comment by leMaik** [comment]
Edit: Sorry, didn't get to fix this last week. :sweat: I'll fix it this week.
