### ISSUE TITLE
Feature request: Validation before new chip added

### ISSUE THREAD

**Issue by pnagy** [TeamWertarbyte/material-ui-chip-input#79]
It would be nice to give a callback to the input which would make it able to validate the newly added chips. When the callback has returned a string that would mean the newly added chip is not valid we can't add it to the list, we don't call the `onChange` and display the returned string as an `errorText`.

**Comment by leMaik** [comment]
Thank you for the feature request! This behavior can already be achieved by using the component in _controlled mode_. You get a `onRequestAdd` callback and then you can decide if you update the value in the state. Please take a look at the [controlled story](https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/stories/ControlledChipInput.js).

I'll mark this as _won't fix_, as I don't really want to make the uncontrolled mode any more powerful than it already is. Controlled mode keeps this component easier on the inside as _you_ (the user) can handle all the logic.
