### ISSUE TITLE
Redundant chips in popover

### ISSUE THREAD

**Issue by Sharlaan** [TeamWertarbyte/material-ui-chip-input#8]
I just discovered this new component which fits perfectly my current needs, very nice job !

Can i mention your project in official MaterialUI issues ? (i have a pending PR about autocomplete with Chips but didnot know about this project)

I also have 2 suggestions about the chips in popover:

1. Whenfirst focusin the input (no value typed), the autocomplete popover should show with all available suggestions.

2. When selecting a suggestion chip from popover, this suggestion should disappear from suggestions list. And vice versa when deselecting a chip from the input, this chip should reappear in suggestions list.
This behavior would make usage more friendly imho.

What's your thoughts ?

**Comment by leMaik** [comment]
I'm happy to see that this component is useful for some people. :) Of course, you can mention this project. I don't know if they'd merge this component into their core library, but if they want, I'd be all for it.

Regarding your suggestions:

- [ ] I'll add an option to display the popover even if no text is entered (if that is possible using `<AutoComplete />`
- [ ] That would be a good enhancement for usability, I'll add that in the next version :+1:

**Comment by leMaik** [comment]
Your first suggestion was already possible using the `openOnFocus` prop. I added it to the props table in the readme so that it is easier to find.

If `openOnFocus` is set to `true`, the menu will open on focus, if there are auto-complete suggestions. That means that you need a filter that has results even without input, which the default filter does not do (it returns no results if there is no input).

I added a story that does what you want, using this code:
```jsx
<ChipInput
  fullWidth
  openOnFocus
  dataSource={['alpha', 'beta']}
  hintText="Try typing a..."
  filter={(search, key) => search === '' || key.indexOf(search) >= 0}
/>
```

**Comment by Sharlaan** [comment]
Just tried, very nice !

Would it be possible to make the filter function as default value, so just have to include "openOnFocus" to get the functionality ?

**Comment by leMaik** [comment]
1.  Thought about that, but I wasn't sure if that should be the default filter. The way it is now, it behaves liek `AutoComplete`, which makes it consistent.
2. I could re-open the menu, but it is [hard-coded](https://github.com/callemall/material-ui/blob/master/src/AutoComplete/AutoComplete.js#L287) to always close when pressing the enter key in the dropdown menu. :confused: I really don't want to write my own `AutoComplete`.

**Comment by Sharlaan** [comment]
1. yes agreed, but the original AutoComplete is designed for a single value selection. Is a ChipInput also supposed to be same design ? Probably not ...

2. Indeed i noiced also this hard coded way for the close(), but maybe a look at my [PR#L247](https://github.com/callemall/material-ui/pull/5018/files#diff-f5a0978e337757ac80c1a1dd2072e1e8) would help you find an easy solution ? (actually i didnot have to change "that" much)

**Comment by leMaik** [comment]
1. Good point, I'll change the default value.
2. I'll look into that in the next days. I think I just need to override the event handler somehow (without copy/pasting `AutoComplete`)

**Comment by leMaik** [comment]
@Sharlaan Didn't get number 2 to work. If you want to do this, a pull request would be highly appreciated. :)
