### ISSUE TITLE
Support of arrayOf(object)

### ISSUE THREAD

**Issue by Sharlaan** [TeamWertarbyte/material-ui-chip-input#9]
Would it be possible to extend dataSource into accepting objects ( {label, value} for example) ?

**Comment by leMaik** [comment]
That would be possible, even without introducing breaking changes! Thanks for the suggestion, I'll add that soon.

**Comment by leMaik** [comment]
After re-reading this issue, I found that this is already possible using `dataSource` and `dataSourceConfig` to specify which attributes should be used for the labels and the values. See the [Auto Complete doc](http://www.material-ui.com/#/components/auto-complete) for more information.

At the moment, this component would use the labels as values, though. I don't really know how to handle this, because the user might create new values that don't distinguish between _label_ and _value_ (but only have a value).
Should I add an option to block users from creating custom chips (with values that aren't present in the data source) and treat custom chips (entered by the user) as _values_?

**Comment by umidbekkarimov** [comment]
@leMaik  Material UI is going to change AutoComplete API soon https://github.com/callemall/material-ui/issues/5062
___
btw Great Job!

**Comment by leMaik** [comment]
@umidbekkarimov They are changing everything soon with the `next` branch and we actually [already started](https://github.com/callemall/material-ui/pull/5291) contributing to it. Thanks for the hint! :+1:

**Comment by takealuke** [comment]
I was able to use chipRenderer to define a function that processes an object to create the chip (using a value from a prop within that object) BUT: when I try to use handleAddChip or handleDeleteChip (which the documentation claims receive "chips" as arguments) I only receive the string value.

To elaborate. here's my code within the chipRenderer function ( where value is { text: <uniqueIDString>, value: <textToBeDisplayed> } ):

`
      let displayText = value;
        if (displayText !== null && typeof displayText === 'object') {
            displayText = value.value;
            key = value.text;
        }


        let chip = (
            <Chip
                key={key}
                style={{ margin: '8px 8px 0 0', float: 'left', pointerEvents: isDisabled ? 'none' : undefined }}
                backgroundColor={isFocused ? blue300 : null}
                onTouchTap={handleClick}
                onRequestDelete={handleRequestDelete}>
                {displayText}
              </Chip>
        );

        console.log(chip.key);

        return chip; 

`

I'm using the unique ID as the "key" for the element -- which I would be able to access if "chips" were actually passed to the handler functions. Any ideas for the right way to make this work? Besides creating a reverse lookup dict from displayed name back to ID?

**Comment by leMaik** [comment]
@takealuke It's cool that you can already achieve this by using a custom `chipRenderer`, that's the way I'd like this feature to be implemented. :+1: The documentation claims that `onRequestAdd` and `onRequestDelete` only receive string values (the value of the chip to be added or deleted), so this is _not_ a bug.
The problem right now is that there is no way to get `onRequestAdd` to be called with a custom object, it's always the string the user entered. This is exactly what blocks this issue. I'll look into this soon.

**Comment by max-l** [comment]
I've been trying to use @takealuke's approach, the only way my custom chipRenderer gets called is if the dataSource fields contains strings, that creates other problems,

If I supply a dataSourceConfig={{text:'label', value: 'value'}},
then I get the  Invalid prop `dataSource[0]` of type `object` supplied to `ChipInput`, expected `string`.
error... 

I'd really love to have that dataSource as array of object working !

**Comment by leMaik** [comment]
@max-l I totally get that you'd love to have this working. At the moment, this feature isn't implemented, I'm afraid. :disappointed: That's why it doesn't work for you. I'll try to implement this this weekend. :+1:

**Comment by chaitanya0bhagvan** [comment]
@leMaik Would love to test out this feature if its ready.

**Comment by leMaik** [comment]
@chaitanya0bhagvan I finally started adding this. :tada: Please take a look at the _key-value-chips_ branch and let me know what you think and if it works!

**Comment by voxbox-io** [comment]
Thanks! I tried but it's not working for me. It still works with standard flat array as dataSource, but not with a custom dataSourceConfig :

    const dataSourceConfig = {
      text: 'text',
      value: 'value',
    }  

The dropdown options do show, but selecting an option from the dropdown doesn't add it as a chip.

I am using MaterialUI 0.16.0

**Comment by leMaik** [comment]
@voxbox-io Are you sure? That worked for me, in the story I added.

**Comment by voxbox-io** [comment]
Quite sure, this simple example is not working for me:

<ChipInput
            dataSource={[{ text: 'Chip 1', value: 'one' }, { text: 'Chip 2', value: 'two' }]}
            dataSourceConfig={{ text: 'text', value: 'value' }}
            defaultValue={[{ text: 'Chip 1', value: 'one' }]}   
/>

It shows default values OK, but clicking on any value from dropdown throws error 'Cannot read property 'refs' of null' at line 212

    if (!this.autoComplete.refs.menu)

**Comment by chaitanya0bhagvan** [comment]
@leMaik Yes I got the same error as @voxbox-io . I cloned your repo and ran your storybook example even that is not working. I am not able to add or delete chips. I tried this code in my project and found that the call backs are not getting called at all.

**Comment by leMaik** [comment]
Allright, allright. :wink:

**Comment by leMaik** [comment]
@chaitanya0bhagvan @voxbox-io I think I fixed this. :) Could you please try again if it works for you now?

**Comment by max-l** [comment]
Just tried this branch : https://github.com/TeamWertarbyte/material-ui-chip-input/commit/a6e266dc18a2649205b563b96a60c1f3919e6ab8 

and I confirm that it works when using a dataSource of objects and setting the proper
 dataSourceConfig

Thanks !

**Comment by voxbox-io** [comment]
Works like a charm now, thanks! 👍

**Comment by leMaik** [comment]
Great! I'll merge the changes into master, then.
A new issue that came to my mind is that it's currently not possible to disallow adding _custom_ chips (with values that are not available in `dataSource`) in uncontrolled mode. I'm not sure if this is something that this component should handle or if this should be left for the reducer to decide in controlled mode. I'd prefer the later approach, but I'd appreciate your feedback.

**Comment by chaitanya0bhagvan** [comment]
@leMaik Works as expected. Thanks for a very useful component.

**Comment by chaitanya0bhagvan** [comment]
@leMaik I am getting a error when I press 'Key Down' to open the autocomplete options.

![Stacktrace](https://cloud.githubusercontent.com/assets/4795989/19641079/32bd5e0a-99fd-11e6-82c6-b7329ed4f12c.png)

**Comment by leMaik** [comment]
@chaitanya0bhagvan Please open a new issue, this doesn't seem to be related to this. :wink:

**Comment by leMaik** [comment]
@chaitanya0bhagvan I can't reproduce the error, but I'm not sure if I did the same steps. Could you please provide a minimal example that produces the error?

**Comment by chaitanya0bhagvan** [comment]
@leMaik You can reproduce this error in your story book. Select **with autocomplete** or **objects as chips, uncontrolled** or **objects as chips, controlled** click on the input and press down arrow twice. As you the autocomplete options an error is thrown in the console.

**Comment by leMaik** [comment]
@chaitanya0bhagvan Thank you! :+1: Moved this to #32.

**Comment by calic39** [comment]
@leMaik I can't get it working when trying @voxbox-io example with custom chip renderer. The autocomplete is showing the results but when I click on the item, chip is not created. Do you have an idea what could be wrong? Thanks!

**Comment by leMaik** [comment]
@calic39 That might be a bug, I'll check that tomorrow. Maybe your `chipRenderer` is not implemented correctly, though. Could you please provide some code?

**Comment by calic39** [comment]
@leMaik Sorry man, you were right, I implemented chipRenderer the wrong way. Thanks for the great work!

**Comment by leMaik** [comment]
@calic39 Glad that I could help! :blush:
