### ISSUE TITLE
Error when passing integer values

### ISSUE THREAD

**Issue by amit1911** [TeamWertarbyte/material-ui-chip-input#90]
I am getting the error 'Invalid prop value supplied' when I pass a list of integer values such as [1, 2, 3]. I think this is because of the following proptypes description:-
```
value: PropTypes.oneOfType([
    PropTypes.arrayOf(PropTypes.string),
    PropTypes.arrayOf(PropTypes.object)
]),
```
Is there a reason why only strings and objects are allowed?

**Comment by leMaik** [comment]
Reason: Me only using strings, then refactoring the component to be a stand-alone component and then adding object values.

So thanks for the request, I'll fix the `propTypes`. You can just ignore the warnung, though. :wink:

**Comment by leMaik** [comment]
Sorry, it's been a while. :sweat: This will be fixed in the next release.
