### ISSUE TITLE
How can I override the 14px margin added to the input with floating label text?

### ISSUE THREAD

**Issue by muxica** [TeamWertarbyte/material-ui-chip-input#91]
[On line 463 of this file, you are running an override to set a margin top](https://github.com/TeamWertarbyte/material-ui-chip-input/blob/779dd9652c9d86d5de6a553ef4fb811ca4c53d47/src/ChipInput.js)
```
const overrideRootStyles = {}
    if (floatingLabelText) {
      overrideRootStyles.marginTop = 14
    }
```
I am trying to figure out how to override this as in a particular use case, it results in too much margin for the space the input exists in.

**Comment by leMaik** [comment]
There is no way to override this at the moment, which is bad. I'll change the order of `overrideRootStyles` and `style` so that custom styles are preferred.

**Comment by muxica** [comment]
Thank you!

**Comment by leMaik** [comment]
Material UI's `TextField` has the same 14px margin, so I won't fix this. As a work-around, you can wrap this component inside a `div` and give that `div` a negative `marginTop` value.

**Comment by ElectricRCAircraftGuy** [comment]
Can you demonstrate giving a negative marginTop value in a div? I'd like to remove the 14 pixels too.

**Comment by ElectricRCAircraftGuy** [comment]
After many hours I found an alternate solution:
