### ISSUE TITLE
Ability limit the number you can select

### ISSUE THREAD

**Issue by techniq** [TeamWertarbyte/material-ui-chip-input#92]
Is it possible currently (or can be added) to limit the number that can be multiselected (to say 3)?

**Comment by leMaik** [comment]
This is possible in controlled mode, you can simply not add chips in the `onRequestAdd` handler.

**Comment by techniq** [comment]
Would this allow the user to still autocomplete/search for another option, but it would then silently ignore it on add?  I was hoping to keep the user from even searching once the limit was hit.

**Comment by leMaik** [comment]
You could set `dataSource` to an empty array when the chip limit is reached.

**Comment by leMaik** [comment]
I'll close this because auto completion is not included anymore and this feature can be implemented on the user's side using controlled mode.
