### ISSUE TITLE
Support for option groups

### ISSUE THREAD

**Issue by techniq** [TeamWertarbyte/material-ui-chip-input#93]
I know the underlying <AutoComplete /> does not have this feature, but I didn't know if you had it on your TODO to add support for option groups (`<optgroup>`), similar to [material-ui-superselectfield](https://sharlaan.github.io/material-ui-superselectfield/#/example4) or [react-select-plus](http://github.hubspot.com/react-select-plus/)?

**Comment by leMaik** [comment]
Sounds like a good idea to me, I'd welcome a PR that adds this. :+1:

**Comment by leMaik** [comment]
Since we don't include the auto completion menu anymore, I'll close this as won't fix. I'd appreciate a PR that adds an example on how to achieve this with react-autosuggest. :+1:
