### ISSUE TITLE
Material-UI 0.17 support

### ISSUE THREAD

**Issue by techniq** [TeamWertarbyte/material-ui-chip-input#94]
Currently the peerDependency is set to [>= 0.15.0 <= 0.16.x](https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/package.json#L44).  Any reason this couldn't be changed to `>= 0.15.0 <= 0.17.x`?

Also React is set to `^15.3.2`.  Could it be relaxed to say (^15.0.0)?

**Comment by leMaik** [comment]
> Any reason this couldn't be changed to >= 0.15.0 <= 0.17.x?

No, we just forgot to bump it when they released 0.17.0 :wink: 

> Could it be relaxed to say (^15.0.0)?

No. Material-UI [requires ^15.4.0](https://github.com/callemall/material-ui/blob/master/package.json#L44) and so do we. Not doing so would require us to put a lot of effort into keeping backward-compatible with old React and Material-UI versions, which is, at this point, unfeasible.

**Comment by saschb2b** [comment]
See #89 for a pull request regarding this

**Comment by leMaik** [comment]
@saschb2b Whoops. :sweat_smile:

**Comment by leMaik** [comment]
Just released v0.13.1, which adds support for Material-UI 0.17.x

**Comment by techniq** [comment]
@leMaik @saschb2b thanks :smile:
