### ISSUE TITLE
increase width of autocomplete menu

### ISSUE THREAD

**Issue by duanefields** [TeamWertarbyte/material-ui-chip-input#96]
Some of my items are wider than the menu. I could use fullWidthInput, but it's way more than I need and it creates an empty line - is there a way to control the width of the menu?

**Comment by leMaik** [comment]
All props we don't handle are passed down to `AutoComplete`. This way, you could try to specify a `menuStyle` prop as documented [here](http://www.material-ui.com/#/components/auto-complete) and try to set a custom width.

**Comment by duanefields** [comment]
That worked, though you have to also set the listStyle to increase the width of the options list

```
 menuStyle={{width: 400}}
 listStyle={{width: 400}}
```

**Comment by leMaik** [comment]
@duanefields Good to know!

**Comment by anirudh9654** [comment]
Didn't work with my Program in material UI 0.20
