### ISSUE TITLE
Anyways to use this with Google Places autocomplete?

### ISSUE THREAD

**Issue by advance512** [TeamWertarbyte/material-ui-chip-input#97]
That is, type place, and when places are selected they are added as chips.

Like here:
https://github.com/kenny-hibino/react-places-autocomplete

**Comment by leMaik** [comment]
This should be possible. You need to fetch the places asynchronously in the `onUpdateInput` handler and then set the `dataSource` once the request is done. Keep in mind that this may result in race conditions, so prevent those e.g. by using a request number and only handling the response of the _last_ request.

Let us know when you have a demo, we might add a link to it. :wink:

**Comment by leMaik** [comment]
@advance512 Did you manage to connect this with Google Places? I'll be closing this as it's been a month without a reply, but feel free to re-open it when new questions arise. :+1:
