### ISSUE TITLE
material-ui 0.17.2 compatibility issue

### ISSUE THREAD

**Issue by techniq** [TeamWertarbyte/material-ui-chip-input#98]
I just upgraded to material-ui 0.17.2 and all my material-ui-chip-input's autocomplete menu's no longer close.  I downgraded to 0.17.1 and the problem went away.  I tried to create a simple test on codepen and webpackbin but struggled (material-ui doesn't provide a umd build so using unpkg seemed to not work for codepen and webpackbin was giving me random errors).

I've been having some performance issues with material-ui-chip-input due to a lot of re-rendering that I've been digging into, but I saw material-ui 0.17.2 might have up to a 30% performance boost due to how their inline styles are being rendered.

**Comment by leMaik** [comment]
I'll look into the 0.17.2 issues. Regarding the performance issues, I can just tell that indeed, there is more re-rendering than optimal, due to us "abusing" the `AutoComplete` component and calling `forceUpdate` on it. This will (hopefully) improve when we port this component to Material UI 1.0.0.

**Comment by leMaik** [comment]
This is caused by https://github.com/callemall/material-ui/issues/6560. Looks like we have to wait for material-ui 0.17.3… :cry:

**Comment by techniq** [comment]
No problem. Thanks for the quick responses.

**Comment by leMaik** [comment]
Material-UI 0.17.3 was [released](https://github.com/callemall/material-ui/releases/tag/v0.17.3) and fixes this issue.

**Comment by techniq** [comment]
👍
